### ISSUE TITLE
pred? that doesn't return true/false - feature request

### ISSUE THREAD

**Issue by AlexBaranosky** [jonase/eastwood#10]
Is it within Eastwood's potential to be able to scan the namespaces of a project for vars whose names end in '?' that evaluate to anything but true or false?

**Comment by vemv** [comment]
As of 2021 we're still pretty far from a standardized approach to 'typing' clojure so this sounds like a good issue to be closed.

Today I would recommend a lightweight linter with rewrite-clj, for this sort of thing. e.g. for each `defn foo?`, create the rule suggesting that they should have a specific `fdef` or spec-like "syntax":

```diff
-defn foo?
+speced/defn ^boolean foo?
```

tools like clj-kondo provide a pluggable API so users of different spec/type libraries can try implementing their own linters.
