### ISSUE TITLE
Lint not run over files that don't declare namespaces

### ISSUE THREAD

**Issue by kilkerran** [jonase/eastwood#101]
Some of my files don't declare namespaces. These do not appear to be picked for Linting. There are no checks reported from them and they do not appear in the == Linting log

**Comment by vemv** [comment]
This was implemented back then with https://github.com/jonase/eastwood/commit/a3d73542aadbaf011e277e647290e920cfb6e5b0#diff-4d87948fd6897f48de8e3956b619c793298ce923a9b9df0fd9e7b0d8287cd991R915
