### ISSUE TITLE
Consider making separate :unused-locals-auto-numbered

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#109]
Many namespaces, including some in core.async, have warnings like these, with no obvious correspondence to the source code, and most likely due to the way some macros are being expanded:

src/main/clojure/clojure/core/async.clj:499:22: unused-locals: let bound symbol inst_8653 never used
src/main/clojure/clojure/core/async.clj:518:17: unused-locals: let bound symbol inst_8712 never used

Consider modifying :unused-locals to _not_ report these, and have a separate :unused-locals-auto-numbered that includes only those.  This would be similar to the current :unused-ret-vals :unused-ret-vals-in-try split.

If done that way, the easiest implementation would be to go by symbol names that contain a match for the pattern _<4-or-more digits>.

**Comment by rmoehn** [comment]
:+1:

**Comment by vemv** [comment]
Merging with https://github.com/jonase/eastwood/issues/394
