### ISSUE TITLE
Provide a way to disable warnings for particular macros, or inside all macro invocations

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#114]
Given that:
- many libraries provide macros
- some of those macros will expand into expressions that Eastwood normally warns about, but having such suspicious-looking expressions in a macro expansion is perhaps perfectly normal
- users of such libraries would find it inconvenient to modify the source code of those libraries in order to disable such warnings (even if there were a way to do so in Eastwood at a per-macro or per-expression granularity, which there is not yet)

It seems that having a way to disable such warnings for particular macros, without modifying the source code of the library, is a desirable thing.  Issue #21 would be able to handle selectively disabling warnings, perhaps even in individual expressions within a macro definition (perhaps tricky inside syntax-quoted forms), but it does not address the issue of disabling warnings in projects you do not wish to edit.

A fairly straightforward 'granularity' for this would be to specify a collection of pairs containing (set of macros, set of linters to disable), where macros are specified by their names, perhaps fully qualified, e.g. korma.core/select, and linters by their keyword names in the Eastwood documentation.

Places these could be put:
- already supported, if they are in the Eastwood options map: project.clj file, ~/.lein/profiles.clj file, command line option map
- new place that might be useful: Some other Clojure-syntax file whose name is specified in one of the places above, in the Eastwood options map.  Allowing one such file to include/load one or more others could be useful to share such disabling across multiple developer projects.
- new place that might be useful: In a normal Clojure source file where the macro is invoked, before it is first invoked.  This has the down-side of needing to be in multiple Clojure source files, if the macro is used in more than one of them.  Probably best not to even implement it, then.

It might be useful to extend this to functions or var definitions inside any namespace.  Not clear if that is useful, but think about it.

**Comment by cichli** [comment]
@jafingerhut Would you consider providing any defaults around this? For example:

```clojure
(clojure.test/is (= (:status val) #{:done}))
```

will cause a `constant-test` warning, whereas the following will not:

```clojure
(clojure.test/is (= #{:done} (:status val)))
```

I'm not sure if suppressing `constant-test` inside the expansion of `is` will cause any useful cases of the warning to be suppressed, but if not I think it would make sense for Eastwood to do this by default.

**Comment by vemv** [comment]
This has been possible for a while via

```clj
(disable-warning
 {:linter :suspicious-test
  :if-inside-macroexpansion-of ...
```

so the issue is safe to close now :)
