### ISSUE TITLE
unused-ret-vals always warns about (is (thrown? Exception expr)) forms?

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#116]
Because the expr's return value is ignored?  It seems pretty clear that the intention here is to verify that trying to evaluate the form throws an exception, so ignoring the return value seems quite reasonable here.  Try to find a precise way to disable such warnings in this case.

One example warning of this kind:

src/test/clojure/clojure/data/finger_tree/tests.clj:120:18: unused-ret-vals-in-try: Pure function call return value is discarded inside body of try: (assoc (apply counted-double-list (range len)) n :x)

Another example:

src/test/clojure/clojure/data/json_compat_0_1_test.clj:69:26: unused-ret-vals-in-try: Should use return value of function call, but it is discarded inside body of try: (read-json "{26:\"z\"")

It should be possible to eliminate these via the enclosing-macros customization technique already implemented for suspicious-expression and constant-test linters.  Overlap with #118 if so.

**Comment by muhuk** [comment]
By trial and error the code below seems to disable this warning:

```clojure
(disable-warning
 {:linter :unused-ret-vals-in-try
  :for-macro 'clojure.core/try
  :if-inside-macroexpansion-of #{'clojure.test/is}
  :within-depth 2
  :reason "thrown? & thrown-with-msg? doesn't care about return value by design."})
```

But unfortunately it disables for all `is` expansions, not just the case of `thrown?`/`thrown-with-msg?`.
