### ISSUE TITLE
Enhance keyword-typos linter

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#127]
It still might be too noisy after these enhancements, but worth a try:
- Current version only looks at (name kw) part, ignoring the namespace.  Include namespaces in comparisons.
- Current version throws exception if it encounters something like ::track/load in tools.namespace, because the ns form is not eval'd before reading that.
- It might be less noisy if the keyword occurrence counts were collected across _all_ namespaces being linted, and the reporting done at the end.  Then keywords that occur in multiple namespaces, but only once per namespace, would be less likely to be reported.
- It would be better if {:keys [a b c]} expressions were detected, even if approximately, and included in occurrence counts.

Some of the things above might become easier if we scanned the ASTs.  Perhaps if we tried to stop the AST walking to avoid stepping into macro expansions outside, perhaps stepping into macros defined into clojure.core but not outside clojure.core, that would avoid reporting keywords that only occur in macro expansions.

**Comment by jafingerhut** [comment]
Some of the bullet points above would be avoided if the linter used the ASTs instead of reading the source code.  I tried it that way some time ago, but there were issues.  I should try again, and see if the issues can be overcome.

One thing that may help with using ASTs, and even if not, would be a good configuration option to add, regardless: Make it easy to add configurations to disable ever warning about particular keywords.  Probably never want to warn about keywords like :line :column :end-line :end-column that tools.reader adds while it is reading, and appear in syntax-quoted forms.

**Comment by vemv** [comment]
Not sure if this linter deserves much more love, nowadays using Spec, Malli etc would suffice and be less prone to a potential false negative.
