### ISSUE TITLE
Either file name, or line/col info misleading for unused-ret-vals warnings with Nov 24 2014 automat

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#134]
And Eastwood 0.2.2-SNAPSHOT as of Dec 27 2014.

The name space is automat.core, so that is the file name.  The line/col info appears to be from wherever the vars in the import-vars form are defined, because those Vars are the values being warned about as unused return values.

It would be good if the line/col info could be accurate for that file, but next best would be for the file names to match the existing line/col info.

**Comment by vemv** [comment]
> The line/col info appears to be from wherever the vars in the import-vars form are defined

Potemkin's `import-vars` is known to assoc more metadata than it should (:file, and accordingly :line / :column) so most likely the issue relates to that.

Potemkin isn't as used these days so supporting it particularly well doesn't seem worth the effort.
