### ISSUE TITLE
Add an annotation to disable all constant-test warnings for a particular Var

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#137]
For example, in some libraries a Var like "DEBUG" is used to enable or disable many optional debug messages, e.g. instaparse does this.  This usually leads to many :constant-test warnings, all with the same condition of that single Var.  Instead of disabling each of them individually, it would be convenient if the Var itself could be configured to tell Eastwood 'never issue a :constant-test warning if the condition is this Var alone'.

**Comment by vemv** [comment]
This is a reasonable feature, otoh nobody has complained over the years.
