### ISSUE TITLE
Emacs 24 goes to wrong column for warnings in lines with tab characters

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#143]
Eastwood reports column numbers in terms of counts of characters, treating tab characters as 1, always.

Emacs 24 compilation-mode buffers seem to treat the column numbers as "after tab expansion", so the cursor goes to the wrong column in the line for lines with tab characters in them.

I don't know if there is anything reasonable to do about this in Eastwood, or whether Emacs has some option to change its interpretation of column numbers in compilation-mode buffers.  I have not tested what Emacs does if you change a buffer's tab stop from the default of 8 spaces.

**Comment by vemv** [comment]
As of lately I'm envisioning Eastwood as less of an editor-oriented solution and more of a CI-oriented one, given its performance characteristics.

So issues related to Emacs integration would be out of scope.
