### ISSUE TITLE
Add i18n support, with first additional "language" being Clint Eastwood style

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#145]
e.g. from justin_smith on #clojure IRC channel:

"so about now you are probably asking, is this the root cause of the exception, or is there another exception left?"

"It's a hell of a thing, killing a Thread.  You free all the resources it ever had, and ever could have." (not strictly true)

Also: This bug could blow your head clean off.

May as well make extensions open to actual languages if this is done.

**Comment by vemv** [comment]
I don't foresee myself implementing i18n (as English is the lingua franca of programmers, and practically no clojure tooling is i18n-ed), so since it's been some 6 years I'll simply close this one.

I guess anybody is free to reopen if planning to contribute a PR
