### ISSUE TITLE
Improve file/line/col tracking for macros expanded, esp when defined in other files

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#148]
This might require re-reading source code for namespaces already loaded before Eastwood begins, because those might be missing the desired annotations needed to make this possible.

Colin Fleming made some custom modifications to riddley's macro expander to better track file/line/col info, I believe, which he used for Cursive's macroexpand-in-editor feature.  I haven't looked through the details yet: https://github.com/cursiveclojure/riddley/blob/master/src/cursive/riddley.clj

**Comment by vemv** [comment]
We could take a look at the topic again whenever we get a user issue report in this specific direction (which hasn't happened in a while).
