### ISSUE TITLE
Idea: hardcoded newcomer-friendly suggestions?

### ISSUE THREAD

**Issue by chenglou** [jonase/eastwood#149]
Haskell linter has some nice beginner-friendly tips for rewrite the code in a more idiomatic way. In clojure you could have something like: `instead of (a (b (c d))), try the macro (->> d c b a)`. The patterns would be hardcoded mostly.

It's hard to discover new functions in stdlib when you don't know about this. This could potentially help a lot. I'm not sure how far you can take this though.

**Comment by jafingerhut** [comment]
This sounds like exactly the kind of thing that kibit does: https://github.com/jonase/kibit

There is also the Clojure cheat sheet for discovering functions in the core library, grouped by similar functionality: http://clojure.org/cheatsheet  http://jafingerhut.github.io

**Comment by chenglou** [comment]
:+1:
