### ISSUE TITLE
Middleware to store eastwood project options somewhere accessible

### ISSUE THREAD

**Issue by venantius** [jonase/eastwood#155]
I'm trying to think about how I can get vim-eastwood to know about a project's eastwood options. There's a naive and brute force implementation under which I actually slurp all of the possible relevant files and merge them, but that feels truly awful. I was wondering if you'd be open to me submitting a PR for some extremely light Leiningen middleware that would create an otherwise empty namespace that would just serve as a holder for the eastwood project options. 

This approach has the advantage of being something that anybody running from the REPL could access as a default for their options, without having to explicitly specify them.

**Comment by jafingerhut** [comment]
So there is already the ability to have an :eastwood key in Leiningen's project.clj if you invoke Eastwood from 'lein eastwood', but I guess you want something that is in a known place where it can be accessed from the REPL?

You are thinking something like a Var in an eastwood-specific namespace like eastwood.config ?

**Comment by venantius** [comment]
Yeah, I had in mind something like `eastwood.config` which only has one var, `*options*` (or without earmuffs, as you prefer). And yes, the notion is to allow the user invoking eastwood from the REPL (or, in  any rate, via that code path) to pass in the project's configuration (or perhaps even to have the project's configuration be the default value for `opts` there).

**Comment by vemv** [comment]
See https://github.com/jonase/eastwood/pull/156#issuecomment-881995229
