### ISSUE TITLE
Don't warn about discarded function value with conj! et al

### ISSUE THREAD

**Issue by expez** [jonase/eastwood#158]
Since there's only a few of these, and they're part of `core`, we should add some exceptions to suppress the warning.

**Comment by jafingerhut** [comment]
The return value of conj! and other transient operations definitely should always be used, unless there is something big I am missing here.  See docs at http://clojuredocs.org/clojure.core/assoc! for example.

Is there some code that you are seeing warnings that you think should not that you could paste here?

**Comment by expez** [comment]
```
user> (def t (transient []))
#'user/t
user> (conj! t 1)
#<TransientVector clojure.lang.PersistentVector$TransientVector@7ee6e880>
user> (persistent! t)
[1]
```

Sometimes I just care about the end value of `t`.  I just want to build the vec efficiently, discarding any intermediate values.

**Comment by jafingerhut** [comment]
The intermediate values are _crucial_ to use with transients, or else you may in some cases end up with the wrong final value, as stated in the link I gave above.

Here is how I think of it: when you use conj on a persistent set X, afterwards X is still usable for further operations on, and the return value of conj is a new set Y that can be operated upon.

When you use conj! on a transient set X, X is _undefined_ (the language does not make it undefined, nor penalize you in any way if you try to use it, but don't use it).  Only the return value Y can be counted upon to have the changes specified by the conj! operation.  X might have them, too, but that is an accident, not guaranteed.

**Comment by jafingerhut** [comment]
If you want another source, check out this page: http://clojure.org/transients

In particular, these sentences:

"Note in particular that transients are not designed to be bashed in-place. You must capture and use the return value in the next call."

**Comment by expez** [comment]
Clearly I'm in the wrong here.  Thanks for taking the time to educate me, I **really** appreciate it!

**Comment by jafingerhut** [comment]
It is a very common mistake with transients, made very easy to misunderstand by the fact that 'bashing them in place' usually works.
