### ISSUE TITLE
A webhook for eastwood on GitHub

### ISSUE THREAD

**Issue by ftomassetti** [jonase/eastwood#159]
First of all thank you for creating this project: it is amazing and it helped me improving the quality of a couple of projects of mine ([effectivejava](https://github.com/ftomassetti/effectivejava), [civs](https://github.com/ftomassetti/civs)).

I would like to run these checks on every pull requests: is there any webhook for running eastwood? Any plan to implement it? I would be glad to help on that side!

**Comment by cichli** [comment]
Try adding this to your `travis.yml`:

```yml
script:
  - lein2 test
  - lein2 eastwood
```

This will run both the tests and eastwood as part of the same job. 

You can also use the Travis [build matrix](http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix) functionality to split them out into separate jobs: see the [travis.yml](https://github.com/cichli/cider-nrepl/blob/master/.travis.yml) from the cider-nrepl project for a more fully fleshed out example.

**Comment by vemv** [comment]
Yes these days CI usage can be inferred from https://github.com/jonase/eastwood#installation--quick-usage
