### ISSUE TITLE
unused-fn-arg reports this on proxy

### ISSUE THREAD

**Issue by phillord** [jonase/eastwood#16]
This simple namespace:

(ns simple.core)

(proxy [Runnable] [](run []))

Produces an unused-fn-args error.

lein eastwood
== Linting simple.core ==
{:linter :unused-fn-args,
 :msg "Function args #{this} are never used",
 :line 3}

I think that is because proxy creates a anaphoric "this". One simple solution would be to specifically ignore "this", but this seems a bit blunt.

**Comment by mrkam2** [comment]
Interesting, I'm seeing the same problem with the most recent version of eastwood `1.4.2` and it complains about `this` in one code while doesn't complain in another. Though the code I'm using is identical: 

```
(System/setErr (PrintStream.
                              (proxy [OutputStream] []
                                (write ([_]) ([_ _ _])))))
```

Macroexpanding the `(proxy ...` part shows that it produces `this` argument:

```

(macroexpand '(proxy [OutputStream] []
                                 (write ([_]) ([_ _ _]))))
(let*
 [p__7276__auto__ (new sample.proxy$java.io.OutputStream$ff19274a)]
 (clojure.core/init-proxy p__7276__auto__ {"write" (clojure.core/fn ([this _]) ([this _ _ _]))})
 p__7276__auto__)
 
 ```

**Comment by vemv** [comment]
Please be advised that `unused-fn-arg` is one of the linters I'd be least interested in maintaining as it's one of those things that clj-kondo does well and where Eastwood's distinct approach doesn't particularly add a unique value.

Maybe a good read: https://clojurians.slack.com/archives/CAGC51YQ7/p1718980530364849

Cheers - V

**Comment by mrkam2** [comment]
Good to know, thanks for the quick response!
