### ISSUE TITLE
Warning when using timbre's profile macro

### ISSUE THREAD

**Issue by ducky427** [jonase/eastwood#161]
When I run the eastwood tool on the following code:

``` clojure
(ns eastwood-check.core
  (:require [taoensso.timbre.profiling :as p]))

(p/defnp my-fun
 []
 (+ 1 1))
```

I get the following warning:

```
core.clj:4:1: constant-test: Test expression is always logical true or always logical false: (clojure.core/keyword? "my-fun") in form (if and__3973__auto__ (clojure.core/and (clojure.core/namespace "my-fun")) and__3973__auto__)
```

Is that the intended behaviour?

Thanks!

**Comment by jafingerhut** [comment]
It certainly isn't desirable.  I have explicitly added configuration to Eastwood to disable many warnings produced by macros in various libraries, including timbre [1], but either haven't seen this one before, or hadn't written any special disabling configuration for it yet.

I can look into the details of this one and see if it is easy to add configuration to disable it, without also masking other useful warnings.  Not sure when next Eastwood release will be (work has been hectic lately, leaving little hobby time).

Given that Eastwood analyzes things after macro expansion, it is pretty easy to write macros that include code that one would never write by hand.

[1] https://github.com/jonase/eastwood/blob/master/resource/eastwood/config/third-party-libs.clj#L60-L64

**Comment by ducky427** [comment]
Thanks @jafingerhut!

**Comment by vemv** [comment]
The `profiling` ns in question has been long deprecated and finally removed in https://github.com/ptaoussanis/timbre/releases/tag/v5.1.0 so the simplest thing we can do is closing this issue - running old versions of Timbre in CI is likely not worth the effort

Eastwood features various ways to disable warnings in a fine-grained manner, e.g.:

https://github.com/jonase/eastwood#eastwood-config-files

https://github.com/jonase/eastwood#ignored-faults
