### ISSUE TITLE
False positive for backref keywords

### ISSUE THREAD

**Issue by georgesimms** [jonase/eastwood#163]
If you try to use `:contoso/_foo` and `:contoso/foo`, eastwood complains

`"Possible keyword typo: :contoso/_foo instead of :contoso/foo?`

and

`"Possible keyword typo: :contoso/foo instead of :contoso/_foo?`

However keywords that have names starting with _ are legal in datomic and represent backrefs and are definitely not the same as the version without the underscore.

**Comment by jafingerhut** [comment]
This is the current behavior of the :keyword-typos linter, and why it is disabled by default.  It currently works by looking for keywords whose names are a small 'edit distance' away from other keywords, e.g. one can be changed into another by inserting, replacing, or transposing only a few characters in the name.

Please read this section of the Eastwood documentation about this linter: https://github.com/jonase/eastwood#keyword-typos

There could be ways to improve it, but without much more significant 'understanding' of your code, there is no way for a lint tool to know which keywords are actually correct, and which are mistakes.

**Comment by georgesimms** [comment]
Given that this applies to all code that interacts with Datomic and not just my own I think it would be a fairly good idea to special-case keywords that differ only by the presence or absence of an initial underscore in their name.

**Comment by jafingerhut** [comment]
This enhancement should be included in the next Eastwood release, 0.2.2.

**Comment by georgesimms** [comment]
thanks!
