### ISSUE TITLE
Consider checking project.clj defproject contents

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#164]
e.g. :dependencies value should be a vector of 2-element vectors of strings (I think?)

Many other such checks are possible.

**Comment by vemv** [comment]
This goes a bit beyond of the current scope of eastwood e.g. t.analyzer powered linting.

Would sound good and reasonably easy to impl as a custom clj-kondo linter (where it serves the most: as immediate, fast feedback instead of feedback that would be obtained anyway through a `lein deps` error)
