### ISSUE TITLE
Some way to suppress a warning

### ISSUE THREAD

**Issue by expez** [jonase/eastwood#165]
I'd like some way to tell eastwood to suppress a warning.

E.g. a magic comment I could add prior to a line or at the end of the line to let eastwood know that this is a false positive or that I don't have a choice but calling that deprecated method.

**Comment by jafingerhut** [comment]
Yes, this is definitely a common thing to have in a lint tool, and one I have thought about adding for some time, and even written some prototype code to add it, but it still isn't ready yet.  Also issue #21.

**Comment by expez** [comment]
Feel like a dick bumping this, but it's been two years and this is just as annoying.

My situation now is that I'm forced to keep using something that's marked as deprecated.  

If anyone else is in this situation I opted to solve this by redefining the var without the deprecated metadata.

**Comment by Bronsa** [comment]
@expez unfortunately the situation is that none of the contributors is as active on the development of eastwood as we used to, so while I understand and share your frustration, the reality is that new features are not a priority and you'll have to wait until either one of us has both time and desire to implement this. Or some good soul comes forward with a PR.
