### ISSUE TITLE
Dangling code linter

### ISSUE THREAD

**Issue by jstrength** [jonase/eastwood#168]
Are there any plans to add a linter that can detect and warn or possible throw an exception for code that is being ran when the namespace is compiled. This is a problem when people accidentally forget to comment/delete the code when they are playing around in the REPL.

**Comment by jafingerhut** [comment]
A nice idea, but do you have any specific thoughts on how one could categorize dangling code?

Obviously top level ns and def* forms should not be considered dangling code.  Occasionally someone wraps one of those in a top level do or let, but that is not terribly common in normal source code files.

Such things are probably significantly more common in test files.

I can imagine prototyping a linter like this, and then trying it out on the 80 or so projects that I often run Eastwood on, to see how many warnings it produces and whether they seem to noisy or not.  It tends to be an iterative process.

**Comment by jstrength** [comment]
Yeah that is what I was thinking, also a way to possibly white list certain forms or namespaces. It wouldn't be perfect for every project, probably would need to be turned off by default. I do think it would take a while to smooth the bumps out of this type of linter. I was thinking about making my own project to do this but I think it would make a lot more sense to be apart of eastwood. What are you thinking about for an mvp for this feature? I have no familiarity with the codebase, but I if you're interested in developing this I wouldn't mind some collaboration on it.

**Comment by vemv** [comment]
This sounds like a good idea to me, have wanted something like this from time to time.

The delicate part is detection - how does one detect that a given top-level form is a "def"? i.e., that it performs `def`, `alter-var-root`, etc. Even after macroexpansion one cannot be sure if any function invoked from the form's body would in turn execute an `alter-var-root`.

So I think this is not possible to detect without instrumenting clojure.core or such. Which would seem quite a big hassle for a thing that tends to be caught in code review processes anyway.

For a heuristics-based approach, perhaps Eastwood is not the best fit as generally the projects aims to be accurate and not need large, hardcoded allowlists/banlists.

Something based off rewrite-clj or tools.reader might be a better fit.

Suggesting to close
