### ISSUE TITLE
Documentation on primitive type hints seems to be incorrect

### ISSUE THREAD

**Issue by michaelklishin** [jonase/eastwood#171]
The docs suggest that the following is the correct way to tag primitives:

``` clojure
;; Correct primitive/primitive-array type hints on Vars
(def ^{:tag 'int} my-int -2)
(def ^{:tag 'bytes} bytearr1 (byte-array [2 3 4]))
(defn ^{:tag 'boolean} positive? [x] (> x 0))
```

but Eastwood complains about incorrect tags unless I change it to

``` clojure
;; Correct primitive/primitive-array type hints on Vars
(def ^{:tag "int"} my-int -2)
(def ^{:tag "bytes"} bytearr1 (byte-array [2 3 4]))
(defn ^{:tag "boolean"} positive? [x] (> x 0))
```

Is my understanding correct that the docs are out of date?

**Comment by jafingerhut** [comment]
Are you using one of the Clojure 1.8.0-alpha* versions, or some older version of Clojure?

**Comment by jafingerhut** [comment]
Added a note to the README early on that there are known problems when using the latest Eastwood 0.2.1 with Clojure 1.8.0-alpha* versions.

**Comment by michaelklishin** [comment]
@jafingerhut I test against  1.6, 1.7, and master. I believe the warning is present with 1.7.

**Comment by jafingerhut** [comment]
I just tried a teensy Leiningen project using Clojure 1.7.0, with nothing in it except these three lines in one namespace useclj17.core, which I believe is the correct way to tag these values for the Clojure compiler:

```clojure
(def ^{:tag 'int} my-int -2)
(def ^{:tag 'bytes} bytearr1 (byte-array [2 3 4]))
(defn ^{:tag 'boolean} positive? [x] (> x 0))
```

I also created namespace useclj17.bar for comparison, which contains your 3 string-based tags above, that I think the Clojure compiler will ignore (at best).

Using Eastwood 0.2.1 and "lein eastwood" command, I got no warnings:

```
% lein eastwood
== Eastwood 0.2.1 Clojure 1.7.0 JVM 1.7.0_45
Directories scanned for source files:
  src test
== Linting useclj17.bar ==
== Linting useclj17.core ==
== Linting useclj17.core-test ==
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
```

Here are the contents of my $HOME/.lein/profiles.clj:

```clojure
{:user {:plugins [[jonase/eastwood "0.2.1"]]}}
```

Is the project you are seeing this on one that is open source and I could try running Eastwood on it myself?

**Comment by michaelklishin** [comment]
@jafingerhut sure, it's http://github.com/clojurewerkz/elastisch

**Comment by michaelklishin** [comment]
Specifically I've discovered this while working on [this commit](https://github.com/clojurewerkz/elastisch/commit/8f6b12f51d60728a1ed5871e4b27bef2d09b7d75).

**Comment by jafingerhut** [comment]
I don't see how you could possibly be getting any Eastwood warnings when running the latest version of Eastwood on Elastisch at all, because when I try it, it gives these warnings about files containing namespace names that do not correspond with their file names, and in that case, Eastwood gives no further warnings unless those are corrected first:

```
% lein eastwood
== Eastwood 0.2.1 Clojure 1.7.0 JVM 1.7.0_45
The following file(s) contain ns forms with namespaces that do not correspond
with their file names:
Directory: /Users/jafinger/clj/tmp/elastisch/test
    File                 : clojurewerkz/elastisch/native_api/aggregations/top_hits_aggregations_test.clj
    has namespace        : clojurewerkz.elastisch.native-api.aggregations.avg-aggregation-test
    should have namespace: clojurewerkz.elastisch.native-api.aggregations.top-hits-aggregations-test
    or should be in file : clojurewerkz/elastisch/native_api/aggregations/avg_aggregation_test.clj

No other linting checks will be performed until these problems have
been corrected.

The 'should have namespace' and 'should be in file' messages above are
merely suggestions.  It may be better in your case to rename both the
file and namespace to avoid name collisions.

Subprocess failed
```

**Comment by jafingerhut** [comment]
When I clone elastisch, checkout commit d0456f653816e144c6500b7e02ada9e512ab8e28, the one just before the commit you mention, then that local copy to make the namespace name correspond with the file name, I get 5 deprecation warnings, 2 unused-ret-vals warnings, many reflection warnings (which come from the Clojure compiler -- Eastwood doesn't implement its own reflection warnings checks but lets the compiler's warnings through).  I don't see any wrong-tag warnings from Eastwood.

**Comment by michaelklishin** [comment]
@jafingerhut sorry, my suggestion was to try the mentioned commit (or master). But indeed this could have been with master, that version's output is at the bottom when all versions are tested.
