### ISSUE TITLE
Don't lint the src/data_readers.clj file

### ISSUE THREAD

**Issue by Malabarba** [jonase/eastwood#172]
This file is used by clojure to set the `*data-readers*` variable. Its content is a plain map, and eastwood complains of the lack of an `ns` form.

Example: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/data_readers.clj

**Comment by Malabarba** [comment]
Hey there, sorry to bother again. Is there a way that I can configure Eastwood to skip a specific file? Or somehow silence this warning? 

In any case, thanks for this great package. 👍

**Comment by jafingerhut** [comment]
Thanks for the report.  Sorry for the delay in replying.  I'm a bit surprised that no one has reported this before, but I guess users of Clojure's data-readers feature intersected with users of Eastwood are a pretty small set :-)

There are not yet any options to Eastwood to cause it to skip specific files.  There are plenty of options for including or excluding particular namespaces, but of course that doesn't help in this case.

I will look into this.  Perhaps one good way to handle this is to disable the warning about no ns form for files defining data readers?

**Comment by Malabarba** [comment]
Yes, that sounds like the easiest option to me. That's any file called
data_readers.clj sitting at the root of a classpath.

See: http://clojure.org/reader#tagged-literals

**Comment by jafingerhut** [comment]
Do you know any open source Clojure projects that have a data_readers.clj file in them that I could test against?  Or could make a simple one that actually uses a data_readers.clj file?  Having something real, or close to it, to test Eastwood against, is helpful.

**Comment by Malabarba** [comment]
There's cider-nrepl, which is where I ran into this. https://github.com/clojure-emacs/cider-nrepl

**Comment by Malabarba** [comment]
There's also spyscope: https://github.com/dgrnbrg/spyscope

**Comment by jafingerhut** [comment]
Sorry, I should have noticed cider-nrepl from your original report of this issue.  I have added cider-nrepl to a list of projects that I frequently test Eastwood on, which will help verify that when I think I have fixed this issue, it is tested to be fixed on a real project.

**Comment by jafingerhut** [comment]
Fixed with this commit: https://github.com/jonase/eastwood/commit/207dca62947dcc49b5e7342de801b219a4db9c11

It should appear in the next release of Eastwood.  I don't have a plan yet for when that will be released.

**Comment by Malabarba** [comment]
Great. Thanks for your hard work!
