### ISSUE TITLE
Check out new wrong-tag warnings with Eastwood 0.2.2 vs 0.2.1 in byte-streams project

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#176]
Are they an improvement over 0.2.1, or worse behavior?

Before: 0.2.1-lein-2.5.3-clj-1.7.0-jvm-1.8.0_11-macosx-10.11.1.txt
After: 0.2.2-snap12-lein-2.5.3-clj-1.7.0-jvm-1.8.0_11-macosx-10.11.1.txt

== Linting byte-streams ==
Entering directory `/Users/admin/clj/eastwood/crucible/repos/byte-streams-2014-11-26'
src/byte_streams.clj:573:1: wrong-tag: Wrong tag: byte_streams.graph.Type@<somehex> on form: channel
src/byte_streams.clj:573:1: wrong-tag: Wrong tag: byte_streams.graph.Type@<somehex> on form: file
src/byte_streams.clj:585:1: wrong-tag: Wrong tag: byte_streams.graph.Type@<somehex> on form: file
src/byte_streams.clj:585:1: wrong-tag: Wrong tag: byte_streams.graph.Type@<somehex> on form: channel
src/byte_streams.clj:604:1: wrong-tag: Wrong tag: byte_streams.graph.Type@<somehex> on form: input-stream
src/byte_streams.clj:604:1: wrong-tag: Wrong tag: byte_streams.graph.Type@<somehex> on form: output-stream

**Comment by vemv** [comment]
In this case Eastwood was correctly reporting an issue, which I've relayed upstream https://github.com/clj-commons/byte-streams/issues/45
