### ISSUE TITLE
Update resource/var-info.edn for recent Clojure versions

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#177]
Write a few words of documentation on what to do when a new version of Clojure is released.

Consider whether to make a separate version of this file for different versions of Clojure, or to have info about vars in this one file that is different for different Clojure versions.

**Comment by jafingerhut** [comment]
Some updates have been done with this commit, but not all new Vars are included yet: https://github.com/jonase/eastwood/commit/870c2cf201622253971f0bd8f6efe80875af731b

The commit after that one adds a new small Leiningen project.clj and code that will help automate the process of finding Vars that are not mentioned in var-info.edn: crucible/check-var-info/project.clj

**Comment by vemv** [comment]
Merged with `Update var-info.edn` https://github.com/jonase/eastwood/issues/236
