### ISSUE TITLE
Update wrong-tag linter and documentation now that CLJ-1232 is resolved

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#178]
http://dev.clojure.org/jira/browse/CLJ-1232

One change that could be made to Eastwood: Don't warn about the case that is fixed by CLJ-1232, no matter what version of Clojure is being used in the code being linted.  If the developer isn't hitting a problem with it, they don't need to be warned about it, and Clojure 1.8.0 will eliminate the need to change their code, anyway.

**Comment by vemv** [comment]
Note to self: I think this is reflected in https://github.com/jonase/eastwood/blob/2008d78f207bb94ede46560dce34d6884a0f876e/src/eastwood/linters/typetags.clj#L138-L141
