### ISSUE TITLE
Lint the contents of cljc files

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#179]
New in Clojure 1.7.0, but not yet read or linted by Eastwood 0.2.2.

**Comment by chadharrington** [comment]
+ 1

**Comment by divergentdave** [comment]
I have a prototype for cljc support working in [this branch](https://github.com/jonase/eastwood/compare/master...divergentdave:reader-conditional-fixes-sloppy). There are just three places that needed fixes to get things running, though I haven't looked at whether the output's correct yet, nor written any tests. I've submitted the first fix as PR #216, and the other two may require some more thought.

**Comment by divergentdave** [comment]
On this topic, `:wrong-ns-form` should allow `:include-macros` as an option key in .cljc files.

**Comment by jafingerhut** [comment]
@jonase - My time/interest quotient has been low enough, and I expect may remain low for a while, that I won't be spending much time on Eastwood for some time.  Would you be willing to let @divergentdave have commit access, if he is interested in that?

**Comment by jonase** [comment]
@jafingerhut sure, if @divergentdave wants it?

**Comment by divergentdave** [comment]
Sure, fine by me. I'm pretty green when it comes to Clojure, so I'll be asking for 👀 on PRs. I'll have some time to work on it, but it'll probably be in fits and starts.

In terms of direction, do you want eastwood to stick to analyzing JVM-targeted Clojure, or do you want separate modes for analyzing Clojure and ClojureScript? The libraries seem to support both, but I imagine the set of linter rules may diverge between the two languages.

**Comment by jafingerhut** [comment]
I'm happy to answer questions and look at code if you want, although I
won't necessarily be the quickest at getting back to you with detailed code
reviews.

Analyzing ClojureScript would make it more useful, but realize that this
code relies heavily on tools.analyzer.jvm for its results, and I believe
that Nicola Mometto has recently decided to mark the corresponding
tools.analyzer.js project as 'not maintained'.  You could ask him whether
he thinks the code is in a good state for use in Eastwood or not.

Andy

**Comment by divergentdave** [comment]
Sounds good, thanks!

**Comment by jonase** [comment]
@jafingerhut I added @divergentdave as a collaborator.

**Comment by MichaelBlume** [comment]
Simply reading .cljc files in clj mode and analyzing them as usual would be really helpful. Clojurescript support would be great later, but I imagine that'll be more work.

**Comment by divergentdave** [comment]
@MichaelBlume FYI, with #216 merged to master, analyzing the JVM half of .cljc files is now supported. If you could install a snapshot from source and let me know what you think, I'd appreciate it.

**Comment by MichaelBlume** [comment]
So I tried that and got a whole bunch of

```test/honeysql/format_test.clj:89:3: constant-test: Test expression is always logical true or always logical false: (clojure.core/seq (clojure.core/list ["SELECT foo FROM bar1 UNION SELECT foo FROM bar2"])) in form (if temp__4655__auto__ (clojure.core/let [more__35__auto__ temp__4655__auto__] (clojure.core/let [result__36__auto__ (clojure.core/apply clojure.core/= a__34__auto__ more__35__auto__)] (if result__36__auto__ (clojure.test/do-report {:type :pass, :expected a__34__auto__, :actual more__35__auto__, :message nil}) (clojure.test/do-report {:type :fail, :diffs (clojure.core/map clojure.core/vector more__35__auto__ (clojure.core/map (fn* [p1__33__37__auto__] (clojure.core/take 2 (clojure.data/diff a__34__auto__ p1__33__37__auto__))) more__35__auto__)), :expected a__34__auto__, :actual more__35__auto__, :message nil})) result__36__auto__)) (throw (java.lang.Exception. "= expects more than one argument")))
```

But I think that might be unrelated to the cljc thing? And be because macroexpanding are/is forms sometimes results in trivial ifs? Is this a common problem when running eastwood over test files?

**Comment by MichaelBlume** [comment]
With that disabled this is super useful, eastwood now catches a bug that we had to have a user report. I'd love to turn it on for our tests in travis, but I think that would require this to be in a published release.

**Comment by jafingerhut** [comment]
If you can isolate the file with that error down to a small example that gives one of those errors, one that you are willing to share publicly, we might be able to determine if the warning is for an actual problem, or a noise warning that should be suppressed.

**Comment by MichaelBlume** [comment]
Oh, this is all in honeysql, it's totally public, but I'll see about
isolating

**Comment by jafingerhut** [comment]
So I just tried these steps to see if I could reproduce the warnings you are seeing, but didn't see any warnings at all.  Let me know if it looks like I am doing something different than you are:
```
% mkdir $HOME/trythis
% cd $HOME/trythis
% git clone https://github.com/jonase/eastwood
% cd eastwood
% lein install

# edit $HOME/.lein/profiles.clj so that it contains at least this:
# {:user {:plugins [[jonase/eastwood "0.2.4-SNAPSHOT"]]}}

% cd $HOME/trythis
% git clone https://github.com/jkk/honeysql
% cd honeysql

% lein eastwood
== Eastwood 0.2.4-SNAPSHOT Clojure 1.8.0 JVM 1.8.0_102
Directories scanned for source files:
  src test
== Linting honeysql.types ==
== Linting honeysql.util ==
== Linting honeysql.format ==
== Linting honeysql.helpers ==
== Linting honeysql.core ==
== Linting honeysql.format-test ==
== Linting honeysql.core-test ==
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
```

**Comment by MichaelBlume** [comment]
Following your exact instructions gets me the same warnings, actually

**Comment by MichaelBlume** [comment]
Hm, but wiping my .lein/profiles and replacing it with *just* the line
about eastwood removes them, so something else I've got installed is giving
me trouble, interesting

**Comment by MichaelBlume** [comment]
Aha, looks like the problem is I have humane-test-output installed,
commenting that out clears up the warnings. Thanks for working with me on
this.

**Comment by MichaelBlume** [comment]
Problem remains even if I upgrade humane-test-output, unfortunately. I
guess I'll probably keep h-t-o installed locally and make eastwood run
automatically in travis, but it'd be nice to make them work together, not
sure which repo to file a ticket with.

**Comment by MichaelBlume** [comment]
For reproducibility: if you make your .lein/profiles.clj look like
```
{:user {:plugins [[jonase/eastwood "0.2.4-SNAPSHOT"]]
        :injections  [(require 'pjstadig.humane-test-output)
                      (pjstadig.humane-test-output/activate!)]
        :dependencies [[pjstadig/humane-test-output "0.8.1" :exclusions [org.clojure/clojure]]]}}
```

You should get the errors I saw

**Comment by MichaelBlume** [comment]
My guess is h-t-o is adding something to the is/are macros that eastwood doesn't like.

**Comment by jafingerhut** [comment]
Funky, but that would make sense.  I quickly scanned through humane-test-output's code, and it does appear to modify the way is/are work, but not by redefining is/are, but I believe through some other functions/macros used by is/are.

**Comment by divergentdave** [comment]
Based on the warning message above, it looks like this is related to their feature that checks for (is (= ...)) being called with only one argument. I think the h-t-o code could be rewritten to do this at macro expansion time, rather than at run time, and that would clean up the nuisance warnings. I'll open an issue over there.

**Comment by MichaelBlume** [comment]
So, the warnings I got being arguably not eastwood's problem, and definitely not anything wrong with this change, any chance of a release?

**Comment by divergentdave** [comment]
Yes, I'll work on it in a couple days. (currently traveling)

**Comment by jafingerhut** [comment]
Closing this issue, as .cljc files have been processed by Eastwood since 0.2.4 release, and the other follow-up comments address a separate issue with human-test-output plugin.  It would probably be a good idea to have a separate notice in the Eastwood documentation about bad interactions with human-test-output, if those cannot be corrected by straightforward changes to Eastwood or human-test-output.
