### ISSUE TITLE
How to not get Prismatic Schema related warnings

### ISSUE THREAD

**Issue by mattiasw2** [jonase/eastwood#183]
What should I do to not get the following two warnings for each schema return type?

````
(s/defn xml->locales [clj-xml] :- locales-schema
  (let [m1 (mutils/xml-only-keep-tag-contents clj-xml "")
````

gives me the following two warnings

````
src\clj\sss4\Xmldb\BO\locales.clj:75:1: unused-ret-vals: Constant value is discarded: :-
src\clj\sss4\Xmldb\BO\locales.clj:75:35: unused-ret-vals: Var value is discarded: locales-schema
````

**Comment by jafingerhut** [comment]
I haven't used schema at all yet, but am aware of it, and frequently test Eastwood on the code in the plumbing project, which uses schema, and it doesn't give warnings like this.  Here is a sample s/defn use from plumbing that doesn't give such warnings:

```
(s/defn explicit-schema-key-map :- {s/Keyword s/Bool}
  "Given a possibly-unevaluated map schema, return a map from bare keyword to true
   (for required) or false (for optional)"
  [s]
  (->> s
       keys
       (keep unwrap-schema-form-key)
       (into {})))
```

Could it be that you have the :- locals-schema in the wrong place in your s/defn, and they should be moved before the arg vector?

**Comment by mattiasw2** [comment]
Yes, you are right!
