### ISSUE TITLE
How to disable a warning for a function?

### ISSUE THREAD

**Issue by didibus** [jonase/eastwood#187]
I want to disable :unused-ret-vals warnings, but only within one function. Is there a way to do that?
If not, how can I disable this linter for the whole project?

**Comment by jafingerhut** [comment]
To disable a linter completely, search for :exclude-linters in the documentation for examples.

There is an issue already created for adding the ability to disable warnings for particular expressions within your source code, but it has not yet been implemented.  Issue #21 and and #165

**Comment by didibus** [comment]
I tried disabling the linter with :exclude-linters, but it seems that it must be done from the command line. I have a configuration file setup, I've used it to disable warnings for some macros. Now, I feel from the doc I should be able to add the :exclude-linters to the configuration file, and it should get picked up, but I seem to fail at doing so.

What should I put in my config file to have the :exclude-linters be picked up?

Thanks

**Comment by jafingerhut** [comment]
When you say config file, do you mean you have an :eastwood key in your Leiningen project.clj file?  Something else?  It isn't clear to me from your question what config file you mean.

**Comment by didibus** [comment]
Maybe I'm not understanding the doc properly. I'm talking about one of my :config-files files. I thought it would merge with the options map.

**Comment by jafingerhut** [comment]
If you want the gory details, this link explains how Eastwood determines the options that it uses: https://github.com/jonase/eastwood#how-the-eastwood-options-map-is-determined

:config-files files contain code that is actually evaluated before Eastwood starts running, but does not affect the 'options map' that is used.  They are a fairly low-level you-really-need-to-know-what-you-are-doing way to customize Eastwood's behavior.  Sorry if that is confusing.
