### ISSUE TITLE
ClassNotFoundException byte[]

### ISSUE THREAD

**Issue by cloojure** [jonase/eastwood#188]
Hi - Tried eastwood for the first time after wanting to for 2 years.  Got an error; minimal example:

`(def Class-byte-array (.getClass (byte-array 0)))`

in an empty project xyz.core namespace.  Error is:

```
== Linting clj.core ==
Exception thrown during phase :analyze+eval of linting namespace clj.core
ClassNotFoundException byte[]
    java.lang.Class.forName0 (Class.java:-2)
    java.lang.Class.forName (Class.java:348)
    clojure.lang.RT.classForName (RT.java:2168)
    clojure.reflect.JavaReflector (java.clj:169)
<snip>
The following form was being processed during the exception:
(def Class-byte-array (.getClass (byte-array 0)))

Shown again with metadata for debugging (some metadata elided for brevity):
^{:line 4}
(^{:line 4} def
 ^{:line 4} Class-byte-array
 ^{:line 4} (^{:line 4} .getClass ^{:line 4} (^{:line 4} byte-array 0)))
```

**Comment by jafingerhut** [comment]
Thanks for the report.  Out of curiosity, are you using latest released version, 0.2.3 ?

**Comment by cloojure** [comment]
Yes, 0.2.3
Alan

**Comment by jafingerhut** [comment]
This is an exception thrown by the tools.analyzer.jvm library while analyzing that Clojure expression.  I don't know why it occurs yet, but have created a ticket on that library here http://dev.clojure.org/jira/browse/TANAL-118

**Comment by ieure** [comment]
I just ran into this as well. Eastwood found some reflection in my code related to wrapping a `byte[]` in a `ByteArrayInputStream`. After correcting that, Eastwood dies. I left a comment on the JIRA, but looks like this isn't a priority for anyone to fix.

**Comment by vemv** [comment]
This has been fixed for a long while, anyway I crafted a specific unit test just now
