### ISSUE TITLE
wrong-pre-post triggers on some valid expressions

### ISSUE THREAD

**Issue by mtravers** [jonase/eastwood#190]
A perfectly valid precondition:

```
(defn request [args]
   {:pre [*api-base*]}
      ...
```

Triggers the warning:
`wrong-pre-post: Precondition found that is probably always logical true or always logical false.  Should be changed to function call?  *api-base*
`

`*api-base*` is declared ^:dynamic, FWIW.

**Comment by jafingerhut** [comment]
So you use that precondition because you want that function to fail if you accidentally bind *api-base* to nil or false before calling it?

Or because some code at run time can bind *api-base* to a value before calling fn request, and it is a bug if it is bound to nil or false?

**Comment by vemv** [comment]
Hey there,

I'm facing this issue too.

> So you use that precondition because you want that function to fail if you accidentally bind _api-base_ to nil or false before calling it? [...]

Something like that, not sure if _exactly_ though.

My usage pattern is

```clojure
;; in the the test helpers directory:
(defn db []
  {:pre [fixtures/*running-system*]}
  (-> fixtures/*running-system* ...))
```

The reason being, that in unit tests the system is a dynamic var, to be bound in `clojure.test` fixtures.

It is possible that for whatever reason one invokes this code without binding a system first (e.g. from REPL evaluation, or a buggy unit test). Then the code should fail-fast, hence the :pre.

cc/ @slipset
