### ISSUE TITLE
unused-namespaces false positive with vars marked ^:const

### ISSUE THREAD

**Issue by camsaul** [jonase/eastwood#192]
It looks like the `:unused-namespaces` linter is giving false positives when only constants are used from another namespace.

Example:
###### `a.clj`

``` clojure
(ns proj.a)

(def ^:const version "1.0.0")
```
###### `b.clj`

``` clojure
(ns proj.b
  (:require [proj.a :as a]))

(defn project-info []
   {:version a/version})
```
###### Error

``` bash
src/proj/b.clj:1:1: unused-namespaces: Namespace proj.a is never used in proj.b
```

**Comment by camsaul** [comment]
I'm seeing the same thing with macros too

**Comment by jafingerhut** [comment]
I've looked into this a bit, and it isn't obvious if there is a quick straightforward way to account for these namespace uses for vars declared with ^:const in other namespaces.  I'll keep the issue open in case someone thinks of a way.

**Comment by vemv** [comment]
This was fixed with https://github.com/jonase/eastwood/pull/363 , anyway I'd add a specific unit test relative to this issue
