### ISSUE TITLE
Is there a way to write exclusions for :unused-locals ? 

### ISSUE THREAD

**Issue by camsaul** [jonase/eastwood#193]
`schema.core/defn` for example triggers this so I have to turn off the whole linter

**Comment by vemv** [comment]
Any of these mechanisms are fine for excluding faults:

* `:if-inside-macroexpansion-of` , which seems good to add relative to  `schema.core/defn` https://github.com/jonase/eastwood/tree/b6cf5e67dec600b7368db012c868103fe8a314ba#eastwood-config-files
* https://github.com/jonase/eastwood/tree/b6cf5e67dec600b7368db012c868103fe8a314ba#ignored-faults which is a more generic mechanism, can silence anything.

I'll close the issue as it's been many years!
