### ISSUE TITLE
Invalid warning `suspicious-expression: merge called with 1 args`

### ISSUE THREAD

**Issue by boris-arkenaar** [jonase/eastwood#194]
On three files in my project I get eight of these warnings:

```
file.clj:1:1: suspicious-expression: merge called with 1 args.  (merge map) always returns map.  Perhaps there are misplaced parentheses?
```

While the merge function is not used at all in those files.

Any idea what might be causing this?
Thanks in advance!

**Comment by jafingerhut** [comment]
Eastwood does macro expansion before analysis, which can sometimes lead to cryptic messages regarding forms in the macroexpanded version.  Unfortunately the file name, line, and column numbers are not always so explanatory in those cases.  There are extra debugs that can be turned on to help determine the origin of these, but their output tends to be large.  You could try adding "{:debug [:all]}" to the options map you run Eastwood with (or use that alone, if you are not currently using any options), preferably also with one namespace at a time, e.g. {:debug [:all] :namespace [my.ns1]} to limit the time and size of the output.  Save the output in a file, and look for occurrences of merge in it.

**Comment by scotthaleen** [comment]
FYI, for anyone else that runs into this. I had hundreds of 
```
.../file.clj:1:1: suspicious-expression: merge called with 1 args.  (merge map) always returns map. Perhaps there are misplaced parentheses?
```

When I investigated, I was able to narrow it down to the [compojure-api](https://github.com/metosin/compojure-api) library. 

```
(require '[ring.util.http-response :refer [ok]])
(require '[compojure.api.sweet :refer [GET]])
(def route (GET "/status" [] :responses {200 {}} (ok "")))
```
Using `macroexpand` you can see on the last line there appears to be an unnecessary call to `merge` on `:responses`  `(clojure.core/merge {200 {}})`
```
(macroexpand '(GET "/status" [] :responses {200 {}} (ok "")))

;;=> 
(compojure.api.routes/create
 "/status"
 :get
 (compojure.api.meta/merge-parameters
  {:responses [{200 {}}]})
 nil
 (compojure.core/wrap-routes
  (compojure.core/make-route
   :get
   #clout.core.CompiledRoute{:source "/status", :re #"/status", :keys [], :absolute? false}
   (clojure.core/fn [request__12989__auto__]
     (compojure.core/let-request [[:as +compojure-api-request+] request__12989__auto__]
       (do (ok "")))))
  (compojure.api.middleware/compose-middleware
   [[compojure.api.coerce/body-coercer-middleware (clojure.core/merge {200 {}})]])))
```

https://github.com/metosin/compojure-api/blob/1.1.3/src/compojure/api/meta.clj#L301
