### ISSUE TITLE
constant-test in 'manifold.deferred/let-flow'

### ISSUE THREAD

**Issue by NeilMenne** [jonase/eastwood#197]
In this particular case, it has to do with async ring middleware, but it looks kinda like:

```
(defn wrap-middlewarez
  [handler]
  (fn [request]
    (let-flow [response (handler request)]
      (cond (exceptional? response) {:status 500 :body "my b"}
            (empty? response)       {:status 204}
            :else                   {:body response}))))
```

I get an error like: `constant-test: Test expression is always logical true or always logical false: :else in form (if :else {:body response} nil)`.

**Comment by finalfantasia** [comment]
`clojure.core/cond` inside a `core.async/go` block also triggers this warinng.
