### ISSUE TITLE
Support Clojure 1.9 namespaced maps

### ISSUE THREAD

**Issue by brabster** [jonase/eastwood#201]
Hi there,

Clojure 1.9 is introducing namespaced maps and they cause an error in kibit. I appreciate that this is an upcoming feature, just a heads-up.

When eastwood encounters a namespaced map, we get:

```
linting failed:
ExceptionInfo Reader tag must be a symbol
    clojure.core/ex-info (core.clj:4718)
    clojure.core/ex-info (core.clj:4718)
    eastwood.copieddeps.dep10.clojure.tools.reader.reader-types/reader-error (reader_types.clj:330)
    eastwood.copieddeps.dep10.clojure.tools.reader.reader-types/reader-error (reader_types.clj:326)
```

**Comment by jafingerhut** [comment]
Thanks for the reminder.  Eastwood definitely needs an update from the tools.reader library to handle this, which Nicola Mometto may have committed to that project already.  I haven't tested it out yet, but will.  Any recommendations on open source projects that already take advantage of this feature on which Eastwood could be tested?

**Comment by brabster** [comment]
My project uses namespaced maps in its tests, eg. https://github.com/brabster/crucible/blob/master/test/crucible/aws/dynamodb_test.clj

I was using eastwood until I hit the problem. Hope that helps.

**Comment by skuro** [comment]
`tools.reader` 1.0.0-RC1 was just released including the support for namespaced maps

**Comment by jafingerhut** [comment]
It isn't in a released Eastwood version yet, but I have recently updated Eastwood source code to use the latest version of tools.reader, which should address this issue.

If you want to try it out to see if it fixes the issue for you before the next Eastwood release, you can check out these instructions for locally installing an unreleased version of Eastwood from source code: https://github.com/jonase/eastwood#for-eastwood-developers
