### ISSUE TITLE
unused-ret-vals warning when modifying a transient with doseq

### ISSUE THREAD

**Issue by hantuzun** [jonase/eastwood#204]
I'm modifying a transient with doseq and eastwood complains. I don't think there's anything wrong with the code snipped below:

```
(let [sorted-recommendations (transient (avl/sorted-map))
      rank (count recommend-to-vector)]
  (doseq [recommendable recommendable-map]
    (assoc! sorted-recommendations (score-fn recommend-to-vector (second recommendable) rank) (first recommendable)))
  (reverse (take-last size (persistent! sorted-recommendations))))
```

results in:

```
src/kirk/ml/als.clj:10:9: unused-ret-vals: Should use return value of function call, but it is discarded: (assoc! sorted-recommendations (score-fn recommend-to-vector (second recommendable) rank) (first recommendable))
src/kirk/ml/als.clj:10:9: unused-ret-vals: Should use return value of function call, but it is discarded: (assoc! sorted-recommendations (score-fn recommend-to-vector (second recommendable) rank) (first recommendable))
```

Could someone confirm me or point out the error on my side please?

**Comment by jafingerhut** [comment]
assoc! and other transient operations are meant to be used in a way where their return values are used, just like you would do with non-transient assoc.  See examples and some text discussing this at these links: http://clojuredocs.org/clojure.core/assoc! http://clojuredocs.org/clojure.core/dissoc!

**Comment by arrdem** [comment]
https://www.conj.io/store/v1/org.clojure/clojure/1.8.0/clj/clojure.core/assoc%21, https://www.conj.io/store/v1/org.clojure/clojure/1.8.0/clj/clojure.core/dissoc%21

There exist cases where transient operations return different structure handles than the one they received as an argument. In these cases, code which assumes all transient operations are update in place will fail.

**Comment by jafingerhut** [comment]
Closing this issue, as I believe the sample code does contain a misuse of assoc! that can result in a subtle bug, and thus Eastwood giving a warning is a good thing.
