### ISSUE TITLE
False positive unused-ret-vals-in-try

### ISSUE THREAD

**Issue by emlyn** [jonase/eastwood#206]
In a clojure.test `(is (thrown? ...))` expression the inner expression will be evaluated inside a try and the return value ignored, so eastwood raises an `unused-ret-vals-in-try` warning.

I.e. this code:

```clojure
(ns testing.core-test
  (:require [clojure.test :refer :all]
            [testing.core :refer :all]))

(deftest a-test
  (is (thrown? Exception (compare [] 1))))
```

Produces this output:
```
== Eastwood 0.2.2 Clojure 1.8.0 JVM 1.8.0_31
Directories scanned for source files:
  src test
== Linting testing.core ==
== Linting testing.core-test ==
Entering directory `/Users/emlyn/testing'
test/testing/core_test.clj:6:26: unused-ret-vals-in-try: Pure static method call return value is discarded inside body of try: (. clojure.lang.Util clojure.core/compare [] 1)
== Warnings: 1 (not including reflection warnings)  Exceptions thrown: 0
Subprocess failed
```

**Comment by emlyn** [comment]
Didn't notice that there was a 0.2.3 release with this fixed.

**Comment by emlyn** [comment]
Actually I just tried it with 0.2.3 and still get this warning

**Comment by jafingerhut** [comment]
One of the reasons that there are separate :unused-ret-vals and :unused-ret-vals-in-try warnings is for cases like this.  :unused-ret-vals is probably the more 'severe' warning, i.e. more likely to indicate something is wrong in your code.  :unused-ret-vals-in-try is more often wrong, specifically because sometimes people evaluate expressions in a try not for their return values, but because they want to see whether evaluating the expression raises an exception.

**Comment by emlyn** [comment]
Thanks. I think `(is (thrown? ...))` is common enough (it's displayed quite high up on https://clojure.github.io/clojure/clojure.test-api.html) that it would be nice for it to be excluded from this check.
Is it something that's feasible? If so I can look into writing a PR for it when I've got a bit of spare time.

**Comment by emlyn** [comment]
I managed to suppress it with
```clojure
(disable-warning
 {:linter :unused-ret-vals-in-try
  :if-inside-macroexpansion-of #{'clojure.test/is}
  :within-depth 3)
```
but that also suppresses other things inside `is` that don't use `thrown?`. I tried using `:if-inside-macroexpansion-of #{'thrown}`, but that didn't seem to work. Is there any way to make it just suppress inside `thrown?`?

**Comment by jafingerhut** [comment]
I would have to check carefully.  clojure.test/is is a very peculiar kind of macro in how it is implemented, with several special cases.  thrown? is not a separate macro, if I recall correctly, but a special symbol recognized and handled by clojure.test/is itself.
