### ISSUE TITLE
False positive :non-dynamic-earmuffs

### ISSUE THREAD

**Issue by emlyn** [jonase/eastwood#212]
Creating a var like `(def ^:dynamic *foo* nil)` provokes the following warning:
```
non-dynamic-earmuffs: #'eastwood-test.core/*foo* should be marked dynamic
```
when it is clearly marked dynamic.

In the source it looks for an `:is-dynamic` key ([here](https://github.com/jonase/eastwood/blob/eb58d6fb2628e1d178d4b8d2c46d4788b2a20094/src/eastwood/linters/misc.clj#L128)), but AFAICT that keyword does not appear anywhere else in the source. Shouldn't it be using `dynamic?` from [here](https://github.com/jonase/eastwood/blob/eb58d6fb2628e1d178d4b8d2c46d4788b2a20094/src/eastwood/copieddeps/dep1/clojure/tools/analyzer/utils.clj#L141)?

**Comment by arrdem** [comment]
Yes, it should be. Patching.
