### ISSUE TITLE
eastwood unexpectedly slow

### ISSUE THREAD

**Issue by ccann** [jonase/eastwood#217]
I have a project with 14 small namespaces and the following eastwood config:

```clojure
:eastwood {:exclude-linters [:constant-test :deprecations]
           :add-linters [:unused-namespaces :unused-private-vars]}
```
Eastwood takes over 30 seconds to run:
```
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
       26.98 real        32.09 user         1.32 sys
```
on a Mid 2014 macbook pro 2.2 Ghz core i7.

Are there any plans to make it speedier? Is a lot of this JVM startup time? I'm just hoping to understand what takes so long and if there's anything we can do to help / speed it up. Really appreciate all the work that went into this library as it's quite useful to us.

**Comment by jafingerhut** [comment]
There is an extra debug option that will print out more elapsed time details in various parts of Eastwood.  Add the key :debug with the value [:time] to your options map, and you should see that info in the output.

**Comment by jafingerhut** [comment]
A chunk of that 30 seconds is starting up at least 1 JVM for Eastwood to run in, and I think 'lein eastwood' might start one JVM for lein, then another for running Eastwood.  That shouldn't be a large fraction of the 30 seconds, but maybe 10%.

**Comment by jafingerhut** [comment]
And one more response to a question of yours I didn't answer before - I have no plans to speed up Eastwood any time soon.  I have done some performance improvements in the past (yes, once it took even longer than it does now).
