### ISSUE TITLE
clojure.test/are false positive

### ISSUE THREAD

**Issue by nha** [jonase/eastwood#218]
`(clojure.test/are [args] {})`
is resulting in a warning

```
constant-test: Test expression is always logical true or always logical false: (clojure.core/seq? map__62079) in form (if (clojure.core/seq? map__62079) (clojure.lang.PersistentHashMap/create (clojure.core/seq map__62079)) map__62079)
```

**Comment by divergentdave** [comment]
I think this is operating correctly. According to the docs for clojure.test/are, there should be three or more arguments. Since there aren't enough arguments here, the template gets expanded zero times, so there aren't actually any test cases that get run.

**Comment by vemv** [comment]
Can this issue be closed?

cc/ @slipset
