### ISSUE TITLE
false positive: "= expects more than one argument"

### ISSUE THREAD

**Issue by technomancy** [jonase/eastwood#226]
```clj
(defn check [x] (if (System/getProperty "not-identity") :never x))

(deftest equality-test
  (let [query  {:key "abc"}
        result (check query)]
    (is (= result query))))
```

This gives `constant-test: Test expression is always logical true or always logical false: (clojure.core/seq (clojure.core/list query)) in form (if temp__4655__auto__ (clojure.core/let [more__69__auto__ temp__4655__auto__] (clojure.core/let [result__70__auto__ (clojure.core/apply clojure.core/= a__68__auto__ more__69__auto__)] (if result__70__auto__ (clojure.test/do-report {:type :pass, :expected a__68__auto__, :actual more__69__auto__, :message nil}) (clojure.test/do-report {:type :fail, :diffs (clojure.core/map clojure.core/vector more__69__auto__ (clojure.core/map (fn* [p1__67__71__auto__] (clojure.core/take 2 (clojure.data/diff a__68__auto__ p1__67__71__auto__))) more__69__auto__)), :expected a__68__auto__, :actual more__69__auto__, :message nil})) result__70__auto__)) (throw (java.lang.Exception. "= expects more than one argument")))`

**Comment by divergentdave** [comment]
See the discussion on #154, you may need to update your installed version of humane-test-output.

**Comment by technomancy** [comment]
That was indeed it; thanks!
