### ISSUE TITLE
Crashes when using :managed-dependencies

### ISSUE THREAD

**Issue by MatthewDarling** [jonase/eastwood#230]
## The issue

As of version 2.7.0, [Leiningen 2.7](https://github.com/technomancy/leiningen/blob/master/NEWS.md#270--2016-08-24) supports Maven's [managed dependencies](https://github.com/technomancy/leiningen/blob/master/doc/MANAGED_DEPS.md).

`leinjacker`, one of the dependencies that are copied into Eastwood, has a bug that prevents using `:managed-dependencies`.

The crash looks like this:

```clojure
$ lein eastwood
Exception in thread "main" java.lang.AssertionError: Assert failed: (dep-spec? dep-spec)
	at eastwood.copieddeps.dep6.leinjacker.deps$dep_name.invokeStatic(deps.clj:23)
```

## Fixing it

I've [gotten a fix merged to master on `leinjacker`](https://github.com/sattvik/leinjacker/pull/13), which would be `0.4.3` if it were released. However, [there's no release yet](https://github.com/sattvik/leinjacker/issues/14).

Since the full source is copied into this repo, in theory the same fix could be applied directly to the source within Eastwood.

**Comment by jafingerhut** [comment]
@MatthewDarling Do you know of any open source project using Leiningen and its managed dependencies that causes the crash without the fix in `leinjacker`, but works better with the new version of `leinjacker`?  If so, I may want to add it to a list of projects that I regularly run Eastwood on.  It would also help verify that I've gotten the right version of leinjacker in to actually fix the issue.

**Comment by jafingerhut** [comment]
From the documentation you pointed me at, I was able to create a tiny little dummy Leiningen project that used the :managed-dependencies key in its project.clj, such that without the new version of leinjacker source code, "lein eastwood" threw an exception, but with the new leinjacker source, it proceeded in what looked to be a normal manner.

Here is the Eastwood commit with the changes, which should look very familiar to @MatthewDarling : https://github.com/jonase/eastwood/commit/0cd2e82e00b21b6e2aaa7abaae5f8c53f2ada5c7

If you want to try it out to see if it fixes the issue for you before the next Eastwood release, you can check out these instructions for locally installing an unreleased version of Eastwood from source code: https://github.com/jonase/eastwood#for-eastwood-developers

**Comment by MatthewDarling** [comment]
The latest from `master` works, and switching back to `0.2.4` brings back the crashes. Looks good to me :)
