### ISSUE TITLE
Warning when using Clojure 1.9

### ISSUE THREAD

**Issue by emlyn** [jonase/eastwood#232]
Clojure 1.9 has a new core function `uri?`, which causes the following warning:
```
WARNING: uri? already refers to: #'clojure.core/uri? in namespace: eastwood.util, being replaced by: #'eastwood.util/uri?
```

**Comment by jafingerhut** [comment]
See the pull request comments for details on how this has been fixed in Eastwood: https://github.com/jonase/eastwood/pull/233
