### ISSUE TITLE
Investigate why latest core.async crashes Eastwood

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#235]
The latest version of core.async in crucible causes Eastwood to crash in some case it doesn't handle regarding type tags on expressions.  It may be buried deep inside core.async's go macro, so may not be easy to track down.

**Comment by vemv** [comment]
Eastwood currently performs its build analysing the entirety of the core.async codebase, without errors.

Things are still not perfect, but we're doing as nicely as tools.analyzer allows (a lib which ideally would get some fixes at some point)
