### ISSUE TITLE
Enhancement: Check for keywords used in s/keys with no corresponding spec

### ISSUE THREAD

**Issue by bfabry** [jonase/eastwood#237]
I'm sure @stuarthalloway would give permission to lift his code here for this https://gist.github.com/stuarthalloway/f4c4297d344651c99827769e1c3d34e9

**Comment by vemv** [comment]
I'm not sure if Eastwood is the best place to strengthen (question?) clojure.spec's semantics. There's https://github.com/metosin/spec-tools, other libs related to spec1, and spec2, Malli, etc.
