### ISSUE TITLE
Consider adding linter to warn about duplicate names in function/macro parameter lists

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#241]
It should not warn about duplicate names that begin with '_', since those by convention are for ignored parameters, but something like this should warn:
```
(defn foo [a a a]
  (+ a a))
```
I don't know yet how tricky this might get with destructuring in arg lists.

Suggested here (and perhaps in other CLJ tickets as well, not sure): https://dev.clojure.org/jira/browse/CLJ-2293

**Comment by jafingerhut** [comment]
May be a duplicate of this issue: https://github.com/jonase/eastwood/issues/225   Certainly related, at least.

**Comment by slipset** [comment]
This seems to be caught by `redefd-vars` in 2.7.0-SNAPSHOT

**Comment by vemv** [comment]
> This seems to be caught by redefd-vars in 2.7.0-SNAPSHOT

Indeed:

```
duplicate-params: Local name `a` occurs multiple times in the same argument vector.
```
