### ISSUE TITLE
Issue with the lein plugin lein-sub

### ISSUE THREAD

**Issue by lprefontaine** [jonase/eastwood#244]
Hi,
I have been trying to run Eastwood through the lein-sub plugin and it fails on the second project
in the list (I think).

The lein-sub project file is as follow:

(defproject maskatel/dependencies "3.0.0"
  :plugins [[lein-sub "0.3.0"]]
  :sub ["common-services" "promethee" "cerbere" "discordance" "discordance-maat" ];  "ether" "discordance" "redevanceIII"]
  )

I used the latest version of Eastwood :
$ more ~/.lein/profiles.clj
{:user {:plugins [[walmartlabs/vizdeps "0.1.6" :exclusions [medley com.stuartsierra/dependency]]
		  [jonase/eastwood "0.2.5"] 
		  [lein-environ "1.1.0"]
                  [lein-ancient "0.6.10"]]}}

I looked at the source code but could not make much of it. If someone could point me in a direction
I could investigate further. The lein-sub plugin has been written a while ago.
 Maybe it's not compatible anymore. If a better alternative exists, I can switch to it but the lein plugin page
did not enlightened me so far.

I attached the traceback (ran lein with DEBUG=1).
[fail.txt](https://github.com/jonase/eastwood/files/1584604/fail.txt)

Any suggestion is welcomed.
Luc P.

**Comment by vemv** [comment]
The attachment indicates there were 4 reported warnings:

```
== Warnings: 4 (not including reflection warnings)  Exceptions thrown: 0
clojure.lang.ExceptionInfo: Subprocess failed
```

Perhaps it was simply a matter of addressing them?

**Comment by vemv** [comment]
I think this is because `lein eastwood` ultimately uses `System/exit`, and not `leiningen.core.main/exit` which would create a cleaner exit condition. cc/ @slipset
