### ISSUE TITLE
Getting error while using flambo library anonymous function

### ISSUE THREAD

**Issue by deepakjangid123** [jonase/eastwood#245]
Hi,
I have written a piece of code.
`(ns flambo-example.core`
`   (:require [flambo.conf :as conf]`
`                 [flambo.tuple :as ft]`
`                 [flambo.api :as f])`
`  (:gen-class))`

`(defn some-fn`
`  "Returns some output"`
 ` [rdd field]`
`  (-> (f/map rdd`
`        (f/fn [e]`
`          (e field)))`
`      (f/distinct)`
`      (f/map-to-pair`
`        (f/fn [e]`
`          (ft/tuple e 1)))))`

Now on running `lein eastwood`, I am getting an error like -

> Exception thrown during phase :analyze+eval of linting namespace flambo-example.core
Eastwood cannot analyze code that uses the values of &env in a macro expansion.

But when I am replacing the anonymous function, `f/fn` by clojure.core in-built anonymous function `fn`, then the error gets resolved and linting gets succeed. 
I am not able to find the problem here. Please help me with this. What is the issue with `f/fn`, while doing `lein eastwood`??

**Comment by jafingerhut** [comment]
Here is a section of Eastwood's README that explains slightly more about this limitation: https://github.com/jonase/eastwood#explicit-use-of-clojure-environment-env

In your case, f/fn is flambo.api/fn

That is define here: https://github.com/yieldbot/flambo/blob/develop/src/clojure/flambo/api.clj#L56-L58

The sfn/ alias in that definition is from here, earlier in that same source file: https://github.com/yieldbot/flambo/blob/develop/src/clojure/flambo/api.clj#L14

The serializable.fn namespace comes from this dependency in the flambo project's project.clj: https://github.com/yieldbot/flambo/blob/develop/project.clj#L12

serializable.fn/fn is defined here: https://github.com/yieldbot/serializable-fn/blob/master/src/clj/serializable/fn.clj#L22

The line highlighted by that link contains the use of `&env`, which Eastwood cannot handle.

**Comment by deepakjangid123** [comment]
Got it. Thanks @jafingerhut
