### ISSUE TITLE
unwanted-ret-vals complains about imports

### ISSUE THREAD

**Issue by lverns** [jonase/eastwood#255]
Given a namespace declaration like the following:

```clojure
(ns ccgq.core
  (:import [java.util.UUID])
  (:require [ccgq.helper :as h]))
```

We get a linting message:

```
== Linting ccgq.core ==
src/ccgq/core.clj:1:1: unused-ret-vals: Constant value is discarded: nil
```

The following aren't all equivalent, but none of them produce a linting message.

```clojure
(ns ccgq.core
  (:import [java.util UUID])
  (:require [ccgq.helper :as h]))
```

```clojure
(ns ccgq.core
  (:import java.util.UUID)
  (:require [ccgq.helper :as h]))
```

```clojure
(ns ccgq.core
  (:import [java.util.UUID]))
```
I'm using Lein 2.8.1 and Eastwood 0.2.5 gives the same message with Clojure 1.8.0 and 1.9.0.

**Comment by vemv** [comment]
```
~ $ clj
Clojure 1.10.2
(ns ccgq.core
  (:import [java.util.UUID]))
Syntax error macroexpanding clojure.core/ns at (REPL:1:1).
((:import [java.util.UUID])) - failed: Extra input spec: :clojure.core.specs.alpha/ns-form
```

...The described ns form has been illegal for some time. A compile-time error from Clojure removes the need to refine Eastwood linting in this case.

In addition, clj-kondo would probably catch this before compilation for even faster feedback!
