### ISSUE TITLE
Is eastwood actively maintained?

### ISSUE THREAD

**Issue by samwagg** [jonase/eastwood#257]
I've been using eastwood for a few days now and I really like it. It's super nifty. However, I'm worried that it isn't currently maintained. For example, this PR to implement custom linters (which I think would be great) hasn't had any activity from a maintainer in months: 

https://github.com/jonase/eastwood/pull/239

Should I consider an alternative tool? I'd welcome any thoughts on this subject.

**Comment by jafingerhut** [comment]
It is volunteer time, and you can see from the commit rate that the volunteer time of myself and the few others who have made commits to Eastwood has been going other places for a while.

Jonas Enlund is the actual owner of the Github repository, even though I have made more commits in the last several years since he created it.  I am definitely open to additional committers who are interested in making changes to the code base, and I think Jonas has been, too.  Interested?

**Comment by samwagg** [comment]
Sure, I am interested in helping out.

**Comment by jafingerhut** [comment]
I have recently put out a call for others who may be interested in driving Eastwood forward to the Clojure Google group, and Erik Assum responded: https://groups.google.com/forum/#!topic/clojure/1HthaQyj5o0

I hope I have it correct that Erik has the account @slipset on Github -- you can also get his email address from the Clojure Google group message.  You may be interested in discussing thoughts with him.

**Comment by slipset** [comment]
Yes, that would be me. 

I’m happy to discuss anything, either here on on (the very newly created) eastwood channel on slack. 

As for what I’d like to get done, in no particular order:
1) merge/close all outstanding PR’s
2) set up CI for eastwood 
3) investigate further the plugin-architecture in https://github.com/jonase/eastwood/pull/239, and maybe make a protocol for linters to implement. 


Erik. 
-- 
i farta

**Comment by slipset** [comment]
I may not need your approval, but I would certainly want your advice.
Does this mean I have commit rights to this repo now? I can't seem to figure this out from navigating through github.

**Comment by jafingerhut** [comment]
Happy to provide advice.  I doubt you have commit rights at this moment.  @jonase Do you mind allowing Erik Assum @slipset to have commit access to this repository, given his interest in further development on Eastwood?

**Comment by jonase** [comment]
@jafingerhut @slipset I added you as collaborator 👍

**Comment by slipset** [comment]
@samwagg Yes, Eastwood is now under active maintenance. I've just received all the permissions I need to do work here, and I imagine I'll be cutting a release either tonight or tomorrow.
