### ISSUE TITLE
:deprecations linter ignoring

### ISSUE THREAD

**Issue by dotemacs** [jonase/eastwood#264]
As per my conversation with @slipset earlier today on Clojurians Slack #eastwood channel, the config for ignoring `:deprecations` is being ignored.

At his request I've created minimal example which shows this issue:

https://github.com/dotemacs/eastwooden

The config is here:
https://github.com/dotemacs/eastwooden/blob/master/eastwood.clj

I run `eastwood` like so:

    lein with-profile +eastwood eastwood "{:debug[:config]}"

The fact that the config is being read is show:

```Loading config file: eastwood.clj```

And the warning still appears:

```
 deprecations: Instance method 'public final void java.lang.Thread.stop()' is deprecated.
```

I've tried different ways of picking up the instance method signature, but no luck.

**Comment by slipset** [comment]
Running your repo with a `eastwood.clj` looking like 
```
(disable-warning
 {:linter :deprecations
  :symbol-matches #{#"public final void java.lang.Thread.stop\(\)"}})
```
makes it run just perfectly.
