### ISSUE TITLE
README does not explain how to use the option to read user-written config files

### ISSUE THREAD

**Issue by johnmaruska** [jonase/eastwood#267]
The section "Eastwood config files" of the README explains that there is support for command line options to change which config files are read, including user-written config files, but does not explain what those options are or how to use them.

**Comment by johnmaruska** [comment]
This is included in README.next.md but hasn't been moved to the actual README quite yet.

**Comment by vemv** [comment]
I expanded the paragraph about `:config-files` (as opposed to `:builtin-config-files`) in https://github.com/jonase/eastwood#eastwood-config-files 

As for the DSL itself, I'm not excessively interested in documenting it, as it can change over time and importantly one shouldn't be using it _much_ - Eastwood tries hard to be precise.

I'm more comfortable with issue reports - often those inform us of greater underlying problems.

Ultimately one can always go over https://github.com/jonase/eastwood/tree/d6ed6797f79213675b329286a21d5c3740badd9c/resource/eastwood/config and learn by example.
