### ISSUE TITLE
Installation error: artifact not found 

### ISSUE THREAD

**Issue by MaciekTalaska** [jonase/eastwood#271]
Hi,

Firstly I would like to say that I am new to Clojure, so it may happen that the problem I am having wih eastwood could be my fault.

When trying to install eastwood on my machine, after creating `profiles.clj` file under `~/.lein` and filling it with `{:user {:plugins [[jonase/eastwood "0.2.7-SNAPSHOT"]] }}` (as stated in the README) I am getting the folliwing error:

```
Could not find artifact jonase:eastwood:jar:0.2.7-SNAPSHOT in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

I then tried to change the version to '0.2.8-SNAPSHOT' as this is what is put into the `defproject` line in `project.clj`, but with no luck:

```
Could not find artifact jonase:eastwood:jar:0.2.8-snapshot in central (https://repo1.maven.org/maven2/)
Could not find artifact jonase:eastwood:jar:0.2.8-snapshot in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```
I have had a look at available versions offered by [clojars](https://clojars.org/jonase/eastwood/versions) and it seems the `0.2.7-snapshot` is not there. When I removed the `-SNAPSHOT` suffix from `~/.lein/profiles.clj` it worked without any warnings.

Q: Am I doing something wrong? Or the documentation (README) should be updated?

**Comment by slipset** [comment]
Readme should be updated
