### ISSUE TITLE
Eastwood 0.2.9 reports version as 0.2.8

### ISSUE THREAD

**Issue by iperdomo** [jonase/eastwood#275]
You can check the code as the tag [`eastwood-0.2.9`](https://github.com/jonase/eastwood/blob/eastwood-0.2.9/src/leiningen/eastwood.clj#L6)

I spend some time trying to understand why my dependencies were not getting updated, then realized that it could be a misleading message:

```
$ grep eastwood project.clj 
            [jonase/eastwood "0.2.9"]]

$ lein eastwood
[...]
== Eastwood 0.2.8 Clojure 1.9.0 JVM 1.8.0_181
Directories scanned for source files:
  dev/src src test
[...]
```

**Comment by slipset** [comment]
Sorry for that. The versioning process is a bit to manual. Working on that.
