### ISSUE TITLE
False `wrong-pre-post:`  with multiple conditions

### ISSUE THREAD

**Issue by JAremko** [jonase/eastwood#276]
Example:
``` clojure
(defn foo [m]
  {:pre [(map? m)(:bar m)]}
  (inc (:bar m)))
```
it gets reported `dbg wrong-pre-post: condition=(:bar m) line=49 test-ast :op=:keyword-invoke`

But the condition is solid:
``` clojure
(foo 1)
;; Assert failed: (map? m)
(foo {:baz 1})
;; Assert failed: (:bar m)
(foo {:bar 1})
;; => 2
```

**Comment by jafingerhut** [comment]
Thanks for the report.  A reasonable improvement to Eastwood's code to avoid this debug message in this case is to add the keyword `:keyword-invoke` to the set of keywords on this line of code: https://github.com/jonase/eastwood/blob/master/src/eastwood/linters/typos.clj#L1031
