### ISSUE TITLE
Open to a PR adding a linter to detect undeclared namespace dependencies?

### ISSUE THREAD

**Issue by lynaghk** [jonase/eastwood#288]
I'm working on a linter to detect undeclared namespace dependencies.
For example:

```clojure
(ns a
  (:require b))

(c.foo)
```

might work by accident if namespace `b` happen to depend on namespace `c`, but would later break if `b` ever removed its dependency on `c` and allowed `a` to load before `c`.

If you feel like this is in scope for Eastwood, I'd be happy to submit a PR containing this linter.
For the name, I'd probably call it `:implicit-dependencies`, but am open to suggestions.
Let me know if you'd like a PR, and thanks for your work on Eastwood!

**Comment by jafingerhut** [comment]
It certainly sounds to me like one of the kind of things Eastwood is intended to do.

**Comment by slipset** [comment]
If @jafingerhut thinks it's a good idea, I'm all for it. I'll just ask you to please do the following:

1) Create a separate ns for the linter, eg `eastwood.linters.implicit-dependencies`
2) Update the Changelog to indicate that there is a new linter in town
3) Update the Readme to indicate that there is a new linter
4) Add any documentation needed for special configs and such.

Happy hacking!

**Comment by lynaghk** [comment]
Sounds good, thanks for the checklist.
I'll test what I have a bit further on an internal codebase and get a PR submitted in the next few days.

**Comment by slipset** [comment]
@lynaghk Your linter broke the build :)
In fact, your test case breaks the build because it uses the macro `lint-test` from `linters-test` which in turn refers to `clojure.pprint/pprint` and `clojure.data/diff`, which are not required into your test-ns `eastwood.test.implicit-dependencies-linter-test`

I would imagine this should be fixed by some kind inside-macro-expansion-thingy?

**Comment by slipset** [comment]
@lynaghk Problem isn't with the tests, its with running eastwood on itself.
So the test captures that your linter will find the unmet dependencies, but the test doesn't
capture that we're getting a lot of false positives, that's where the problem lies, and what's shown when you run eastwood on itself:

```
✔ ~/Documents/github.com/eastwood [:2e93a99|…4⚑ 1]
13:28 $ lein eastwood
== Eastwood 0.3.2-SNAPSHOT Clojure 1.8.0 JVM 1.8.0_152
Directories scanned for source files:
  src test
== Linting eastwood.version ==
== Linting eastwood.util ==
== Linting eastwood.linters.implicit-dependencies ==
== Linting eastwood.passes ==
== Linting eastwood.linters.typetags ==
== Linting eastwood.error-messages ==
== Linting eastwood.analyze-ns ==
== Linting eastwood.linters.unused ==
== Linting eastwood.linters.deprecated ==
== Linting eastwood.linters.typos ==
== Linting eastwood.linters.misc ==
== Linting eastwood.lint ==
== Linting leiningen.eastwood ==
== Linting eastwood.versioncheck ==
== Linting eastwood.test.linters-test ==
== Linting eastwood.test.implicit-dependencies-linter-test ==
Entering directory `/Users/erik/Documents/github.com/eastwood'
test/eastwood/test/implicit_dependencies_linter_test.clj:7:1: implicit-dependencies: Var eastwood.lint/lint-ns-noprint refers to namespace eastwood.lint that isn't explicitly required.
test/eastwood/test/implicit_dependencies_linter_test.clj:7:1: implicit-dependencies: Var clojure.data/diff refers to namespace clojure.data that isn't explicitly required.
test/eastwood/test/implicit_dependencies_linter_test.clj:7:1: implicit-dependencies: Var clojure.pprint/pprint refers to namespace clojure.pprint that isn't explicitly required.
== Linting eastwood.test.cc-compare ==
== Warnings: 3 (not including reflection warnings)  Exceptions thrown: 0
✘-1 ~/Documents/github.com/eastwood [:2e93a99|…4⚑ 1]```

**Comment by lynaghk** [comment]
@slipset Ah, death by irony here. = )

What do you think we should do?
Options:

1. Writeup some caveats about macros in the linter docs and don't run this linter by default (this should solve the immediate problem of the linter breaking the build, no?)

2. Try to update the linter so that it can properly handle this situation. I haven't worked with tools analyzer much, so I'm not sure how difficult it'd be to implement the rule, "don't warn when implicit dependencies occurred via expansion of a macro from a namespace that *did* declare those dependencies".

Is it possible for a linter to get all asts from all namespaces at once, so that the linter can do this analysis based only on the arguments it's called with?
Or would the linter need to rely on implicit global state to determine the dependencies of other namespaces?

**Comment by slipset** [comment]
I'd really prefer 2. Since I see on my relatively involved codebase that it returns very many false positives.
There is a 
https://github.com/jonase/eastwood/blob/master/src/eastwood/util.clj#L942
which you might be able to use/take inspiration from

This is unfortunately not my area of expertise. @jafingerhut might also have some tips.

**Comment by lynaghk** [comment]
@slipset I'm definitely open to fixing. I'll let @jafingerhut weigh in on possible impl options for how the linter can work properly with macroexpanded forms.

Are all of the false positives on your codebase related to this macro issue or were there other kinds?

**Comment by jafingerhut** [comment]
Eastwood macro expansion often leads to false positives in several linters without extra care being taken, but it has also at times made it easier to detect certain problems, so definitely a double-edged sword.

In this case, perhaps a straightforward thing to try would be to change the implicit-dependencies linter to never issue warnings for code generated from code within macro expansions, if that macro is defined in a different namespace? (but do give warnings if the macro was defined in this namespace)   i.e. let the listing of that other namespace take care of implicit-dependencies warnings when listing that other namespace, and only worry about this namespace now when linting it.

I don't have the AST data structure produced by tools.analyzer memorized or anything.  I usually start with small examples of code that produce undesirable warnings, as well as small examples of code that I _want_ to produce undesirable warnings, do debug prints of the AST contents, and look for differences between them.

**Comment by jafingerhut** [comment]
FYI, I have been testing older and latest Eastwood versions against the projects in the crucible set of projects (and updating many of those projects to be more recent versions, too, since some of them have not been updated in a long time).

One project named carmine has about 20-30 warnings if you disable the new `:implicit-dependencies` linter, and jumps to a little over 1000 warnings if you enable it.  There are at least a couple of other projects where similar things occur.

**Comment by lynaghk** [comment]
@jafingerhut Yeah, I was able to replicate the warning on some other projects --- turns out that the giant internal codebase I'd been testing against doesn't use any macros across namespaces, which is why I never ran into that issue.

I'll try updating the linter as you suggested to ignore vars introduced by macros from other namespaces.

**Comment by lynaghk** [comment]
@slipset Two things:

1. Since you merged in my fix, would you say it's okay to close this issue?

2. Do you have an ETA for the next Eastwood release? Anything I can do to help get it out the door? (I'd like to be able to refer to an upstream version of Eastwood from our CI.)

Thanks!

**Comment by slipset** [comment]
1) Yes
2) No, but I’ll see if I can’t release it tonight CET. 

Thank you for Borge the contributions and the reminder!

Erik. 
-- 
i farta
