### ISSUE TITLE
Add to README instructions on using tools.deps to run Eastwood

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#289]
I am creating this issue as a reminder for myself to do this.  Seems like a useful thing to have given that tools.deps is getting more well known and used in the Clojure world.

Some notes copied and pasted from a discussion on Slack that may be a good start:

seancorfield [9:47 AM]
@orestis
```
clj -Sdeps '{:deps {jonase/eastwood {:mvn/version "0.2.8"}}}' -e "(require '[eastwood.lint :as e])" -e '(e/eastwood {:source-paths ["src"] :test-paths ["test"]})'
```
You could squirrel most of that away in your `~/.clojure/deps.edn` file as an alias...

seancorfield [9:51 AM]
```
:eastwood {:extra-deps {jonase/eastwood {:mvn/version "0.2.8"}}
             :main-opts ["-e" "(require,'[eastwood.lint,:as,e])"
                         "-e" "(e/eastwood,{:source-paths,[\"src\"],:test-paths,[\"test\"]})"]}
```
(note that you need `,` instead of space!)

orestis [10:01 AM]
Yeah, I saw that trick on your dot-Clojure and was about to ask! Is that a known bug?
I guess though I can just as easily make a tiny namespace to do this.

seancorfield [10:07 AM]
@orestis It's to do with how the strings are run through the `clojure` shell script and into the main opts cache file and then read back. So, yeah, it's a "known feature" :slightly_smiling_face:

orestis [1 day ago]
I ended up doing this:
```
  :eastwood {:extra-deps {jonase/eastwood {:mvn/version "0.2.8"}}
             :main-opts ["-m" "eastwood.runner"]
             :extra-paths ["test" "tools"]}
```
And I made a tools directory to contain simple namespaces like that. In this case:
```
(ns eastwood.runner
  (:require [eastwood.lint :as e]))

(defn -main [& args]
  (e/eastwood {:source-paths ["src"] :test-paths ["test"]}))
```

seancorfield [1 day ago]
Oh, that's nice! :thumbsup::skin-tone-2:

**Comment by slipset** [comment]
I've added a rudimentary `deps.edn` to master.

**Comment by arichiardi** [comment]
This is nice to see, thank you for pasting it

**Comment by glittershark** [comment]
@jafingerhut or @slipset any way we could get a new version published to Clojars that includes this?

**Comment by slipset** [comment]
I’ll have it out by the weekend.

**Comment by slipset** [comment]
@glittershark 0.3.4 is released. Enjoy :)

**Comment by glittershark** [comment]
Thanks @slipset!
