### ISSUE TITLE
Allow unused-meta-on-macro to be disabled

### ISSUE THREAD

**Issue by gzmask** [jonase/eastwood#303]
I wonder why this warning can not be disable: https://github.com/jonase/eastwood#unused-meta-on-macro

As one wants to run lein eastwood on jenkins pipeline, not having a normal return of the command could introduce more efforts.

**Comment by jafingerhut** [comment]
Most Eastwood linters can be disabled completely by using the `:exclude-linters [ ... ]` option.  Search for `:exclude-linters` in Eastwood's README for examples.  Note that this disables that category of lint check for that entire Eastwood run, no matter where such warnings might occur.

You can also disable it for one namespace by doing two runs of Eastwood: the first on just that namespace, with that linter disabled, and the second on all other namespace, with that linter enabled.  That gets to be more than two Eastwood runs if you want to customize the set of linters on more namespaces, of course.

If you want to disable one particular warning on one line of one source file, then most Eastwood linters have no way to do that, e.g. the way other lint tools let you put a specially formatted comment near the line of code that causes the warning.  No one has implemented this feature for Eastwood yet.  https://github.com/jonase/eastwood/issues/165

**Comment by slipset** [comment]
Not arguing that it shouldn't be possible to disable this warning, but if you could give an example of the code which causes Eastwood to emit the warning, and possibly explain why the workaround mentioned in the documentation for this linter is not applicable, it would be very interesting.

**Comment by gzmask** [comment]
Hey @slipset, the code is an upstream library so it's out of my control. If by workaround you mean `:exclude-linters [ ... ]`, the reason is that I feel it's iffy to have some exclusions in eastwood config file, while having this particular one inside project.clj. 

Also this is more of an improvement request rather than a bug report. Feel free to say no if you don't feel this being priority.

**Comment by slipset** [comment]
Not saying no yet :), just trying to understand. May I ask what upstream library you're having problems with (and file/line in that lib)?

**Comment by gzmask** [comment]
Yes, I created a PR already: https://github.com/kumarshantanu/stringer/pull/2/files
Considering the fact that unused metadata isn't creating any reflection warning, I don't really see the necessity to merge it if author isn't using eastwood.

**Comment by slipset** [comment]
May I suggest having a look at https://github.com/expez/superstring which is under active development?

**Comment by slipset** [comment]
If I can ask you one last favour: Could you create a minimal git repository which reproduces the behaviour?

**Comment by vemv** [comment]
Looks like :unused-meta-on-macro should get a similar treatment to https://github.com/jonase/eastwood/pull/372 https://github.com/jonase/eastwood/pull/371, i.e. not every linter currently supports the [disable-warning](https://github.com/jonase/eastwood/tree/c5b7d9f8ad8f8b38dc7138d853cc65f6987d6058#eastwood-config-files) mechanism.

Another fine-grained mechanism is [:ignored-faults](https://github.com/jonase/eastwood/tree/c5b7d9f8ad8f8b38dc7138d853cc65f6987d6058#ignored-faults) which would work nicely today
