### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by vemv** [jonase/eastwood#309]
Hi,

I'm aiming to run eastwood constantly as part of my repl "reloaded" workflow. Only changed files will be analyzed (btw, nice work with https://github.com/jonase/eastwood/commit/0d856cb17d4fd3bf1d08fa4a800bbdee7bedb817 !)

It's working nicely. The only nuisance is that there's too much "wrapping" output, particularly for the case where there 0 warnings for a given ns.

Say I just changed the `user` ns, it having zero faults. This will be the output:

```
:reloading (user)
== Eastwood 0.3.5 Clojure 1.10.0 JVM 1.8.0_192 ==
Directories scanned for source files:
 
== Linting user ==
== Linting done in 920 ms ==
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
user> 
```

What do I see as wrong here:

* The prelude:

```
== Eastwood 0.3.5 Clojure 1.10.0 JVM 1.8.0_192 ==
Directories scanned for source files:
```

* Very importantly, the `== Linting user ==` bit. This ns turned out to have no warnings, but the process was printed anyway.

This becomes a nuisance if see `== Linting <ns> ==` dozens of times, all of them empty. Normally I will `(refresh)` a lot, with zero faults, so seeing all this noise would be tiresome (and hide real faults).

* The outro:

```
== Linting done in 1347 ms ==
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
```

---

So, I propose a "silent mode" in which:

* there's no intro/outro
  * information from failures can be inferred from the presence of individual failures
  * empty output = all OK
* Eager `== Linting <ns> ==` bit is replaced with a lazy `== Found error in <ns> ==`.

The 'API'  would be a new config option for `eastwood.lint/default-opts`: `:silent? true`

WDYT?

I certainly am willing to offer a PR. Just let me know if there's something you disagree with.

Cheers - Victor

**Comment by vemv** [comment]
(Also the `entering <directory>` printlns seem redundant)

**Comment by slipset** [comment]
I’d be happy to receive a PR for this. 
I’ll let you decide what you’d want to see of output.

**Comment by vemv** [comment]
Hey,

awesome, thanks!

I realised I could achieve all I wanted by wrapping `eastwood` with `with-out-str`, then stripping the undesired lines.

That might do for me for a long time, so I'll close the issue for the time being. But good to know about this feature being welcome!

**Comment by NoahTheDuke** [comment]
I would be willing to open a PR for this if there's still interest, as I have such a use case.

**Comment by vemv** [comment]
Is your use case from the repl or from the CLI?

**Comment by NoahTheDuke** [comment]
From the CLI.

**Comment by vemv** [comment]
I'd consider a PR that provided that reporter, so you / anyone could use it without a custom wrapper.

Plus a facility to choose said reporter e.g. `:reporter :quieter`

But probably I wouldn't consider a simpler PR e.g. conditionally silencing `println`s.

**Comment by NoahTheDuke** [comment]
It seems I misread your "silent" mode, and don't need the "lazy `== Found error in <ns> ==`" bit. My apologies for the hasty reading.

I want Eastwood to _only_ print the `src/my/namespace.clj|90 col 42| suspicious-expression: ->> called with 1 args. ...` messages. If I could have it customizable to print the summary at the end, that would also be nice, but I'm fine with only errors.

**Comment by vemv** [comment]
It also sounds like something a custom Reporter could do. We could have a handful of custom reporters, ready to choose.

So https://github.com/jonase/eastwood/issues/309#issuecomment-1113423670 would still apply
