### ISSUE TITLE
CircleCI checkout nullifies `.eastwood` file timestamp check for only-modified files

### ISSUE THREAD

**Issue by dijonkitchen** [jonase/eastwood#316]
In an attempt to try out the new `:only-modified true` eastwood stuff with the `.eastwood` file, it works locally, but I can't integrate it into CircleCI. Seems CircleCI doesn't use the `.eastwood` file somehow?

**Comment by dijonkitchen** [comment]
@jonase have you gotten the incremental check to work in CI?

**Comment by vemv** [comment]
Intuitively, `:only-modified` won't magically figure out the `git diff` between the feature branch and your master branch

**Comment by dijonkitchen** [comment]
Right, that's what the timestamp in the `.eastwood` file captures and it'll run it based on files modified only since that time, but it seems when I run it on CircleCI, it doesn't recognize that file somehow. 

I can get it to do the proper behavior when running locally on my own computer and make sure that CircleCI knows the file exists, but the `lein eastwood` command isn't capturing it in CircleCI's environment I think.

**Comment by vemv** [comment]
It could happen as well that CircleCI Git clones lose "modified-at" file metadata. After all I don't think modified-at is part of what Git intends to store.

**Comment by dijonkitchen** [comment]
Hm... interesting. Not sure how to check that in CircleCI.

**Comment by vemv** [comment]
Either way, you probably can do something like this in Circle:

```
git diff master --name-only | eastwood_command
```

eastwood_command is an hypothetical script that either calls `lein eastwood`, or the Eastwood JVM API from a vanilla clojure program

**Comment by dijonkitchen** [comment]
That's a great idea, but unfortunately the syntax parses a clojure map with source paths or namespaces: https://github.com/jonase/eastwood#installation--quick-usage

**Comment by vemv** [comment]
[read-ns-decl](https://github.com/clojure/tools.namespace/blob/baa4b4ece4192b835c8342cb39dc15e1ceff78a7/src/main/clojure/clojure/tools/namespace/parse.cljc#L39) plus [name-from-ns-decl](https://github.com/clojure/tools.namespace/blob/baa4b4ece4192b835c8342cb39dc15e1ceff78a7/src/main/clojure/clojure/tools/namespace/parse.cljc#L117) would give you that in an hypothetical Clojure program

I have one such program in the oven, it's closed-source for now, but a basic git + tools.namespace tool should be quick to implement

**Comment by dijonkitchen** [comment]
I kind of gave up on this, but think you're right that the git checkout in the CI basically has new timestamps so everything seems new compared to the `.eastwood` file's timestamp. Perhaps a different implementation of this would be better for CI usage.

**Comment by vemv** [comment]
> I have one such program in the oven, it's closed-source for now

(Said program is https://github.com/nedap/formatting-stack)
