### ISSUE TITLE
`warning-enable-config-atom` should be `reset!` on each run

### ISSUE THREAD

**Issue by vemv** [jonase/eastwood#317]
Hi there,

I use Eastwood as a plain library:

`(eastwood/eastwood ...)`

I noticed that on each run, `(count @eastwood.util/warning-enable-config-atom)` keeps growing.

this results in each run taking ~50ms more than the previous one (obviously this will depend on the actual workload).

I did verify that `(reset! eastwood.util/warning-enable-config-atom [])` fixes this performance defect.

Cheers - V

**Comment by slipset** [comment]
Ah, cool!

I seem to remember looking at this code and being pretty puzzled about it, but left it as is because it doesn't cause any harm.

A better implementation, IMO, would be to get rid of the atom all together and rather pass the list around where needed.

PR welcome ;)

**Comment by vemv** [comment]
(normally I avoid creating tiny PRs to third parties... often the feedback loop can be costlier than if the maintainer did the fix himself)
