### ISSUE TITLE
Lint for if without else clause?

### ISSUE THREAD

**Issue by magnars** [jonase/eastwood#32]
Check out this fun bug:

``` cl
(let [result (service/create-stuff ...)]
    (if (:error result)
      {:status 500
       :body result})
    {:status 204})
```

Maybe eastwood could complain about `if` with no else clause - and suggest using `when` instead if that's what you mean?

**Comment by vemv** [comment]
clj-kondo provides a linter for this one. It's a good fit for this kind of thing, and surely implementing a full-blown linter for `if` with Eastwood would further increase the performance bill and maintenance burden.

Sounds good to close?
