### ISSUE TITLE
lein plugin exception

### ISSUE THREAD

**Issue by iyedb** [jonase/eastwood#326]
When typing `lein` in a lein project configured with the eastwood plugin, the following is printed out:
```
leiningen.eastwood  Problem loading: Wrong number of args (0) passed to: leiningen.eastwood/help
```
A brief description of the command is expected as in 
```
cljfmt              Format Clojure source files
```

Also shouldn't be just

```
eastwood            lints Clojure files ...
```
instead of `leiningen.eastwood         lints Clojure files`

**Comment by jafingerhut** [comment]
With Leiningen version 2.8.1 and 2.8.3, and several versions of Eastwood that I tested with versions 0.2.6 and later, this line of output appears in the output of `lein help`:
```
eastwood            Lint your Clojure code.
```
With Leiningen 2.9.1 and Eastwood versions 0.3.0 and 0.3.5, I see output similar to what you do:
```
leiningen.eastwood  Problem loading: Wrong number of args (0) passed to: leiningen.eastwood/help
```
This appears to be something that has changed in Leiningen in recent versions, that Eastwood is using some older Leiningen API to achieve.

**Comment by iyedb** [comment]
Yeah sorry I forgot to specify the versions leiningen and eastwood. 2.9.1 and 0.3.6 respectively.
I have `:plugins [[jonase/eastwood "0.3.6"]]` in my `project.clj`
