### ISSUE TITLE
deprecations warning for java.util.Date(Long)

### ISSUE THREAD

**Issue by svenlaater** [jonase/eastwood#329]
Eastwood complains that `Constructor 'public java.util.Date(java.lang.String)` is deprecated when actually `java.util.Date(Long)` is used in code (which is not deprecated) https://docs.oracle.com/javase/7/docs/api/java/util/Date.html#Date(long)

Example
```
(defn expiry-date 
  "returns a Date object representing current date + 1 millisecond"
  []
  (-> (Date.) .getTime inc Date.))
```

**Comment by positron** [comment]
Workaround:

```
(disable-warning
    {:linter :deprecations
     :symbol-matches #{#"^public java\.util\.Date\(java\.lang\.String\)$"}})
```

**Comment by vemv** [comment]
I wasn't able to reproduce this one, even with a precise unit test which is executed over a CI matrix (different JDKs, clojure versions).

Perhaps this got fixed on its own at some point?

Either way feel free to try Eastwood 0.5.0 (released just now). Would actually appreciate knowing if there still was an issue.

**Comment by svenlaater** [comment]
I am not able to reproduce it either anymore. I guess it is fixed :)

**Comment by vemv** [comment]
Cheers 🍻
