### ISSUE TITLE
Exception "has been given type tag 'null'" thrown when analyzing defrecord body using core.async/go macro

### ISSUE THREAD

**Issue by clov0** [jonase/eastwood#330]
Eastwood gives this error
```
Exception thrown during phase :analyze+eval of linting namespace stellar.single-runner.components.om.core
Local name 'G__26394' has been given a type tag 'null' here:
nil

dbgx for case :op :local tag=null (class form)=class clojure.lang.Symbol (sequential? form)=false form=
G__26394

```
While analyzing this code

```clojure

(defrecord Old-OM [om-config client-id access]
  component/Lifecycle
  (start [component]
    (async/go
      (prn "FASF")))
  (stop [component])
)

```
A minimal repo demonstrating this problem is [here](https://github.com/clov0/sample)
moving the async/go out to a function fixes the issue

**Comment by vemv** [comment]
Thanks much for the report! I kept it in mind for many months. While it's not something Eastwood can fix directly (as this is a concern of its tools.analyzer dependency), now Eastwood 0.6.0 handles core.async more gracefully and typically won't throw exceptions.

Feel free to try it out.
