### ISSUE TITLE
:pre/:post regression

### ISSUE THREAD

**Issue by vemv** [jonase/eastwood#334]
In https://github.com/jonase/eastwood/pull/333/files#diff-a98a186a53e7c0d0afd8a9b3efa1b3a6R1011, the set comparison is wrong - it should be instead e.g.:

```clj
(contains? #{nil false} (-> test-ast :var meta :dynamic)) ;; or just use `not`
```

b/c `(#{nil} nil)` doesn't return `true`.

This results in the following code not being reported as faulty:

```clj
(def logical-false false)

(defn example []
  {:pre [logical-false]}
  42)
```

**Comment by slipset** [comment]
@vemv would you mind taking my branch for a spin and see if it is correct? I can make a new release shortly after you've verified.

**Comment by vemv** [comment]
Morning! Trying.

**Comment by vemv** [comment]
Verified with a Lein checkout. in formatting-stack we have a test that fails if using the checkout @ `master`, and passes @ `fix-334`

**Comment by slipset** [comment]
Deployed to Clojars in 0.3.9
