### ISSUE TITLE
False positive: redefd-vars

### ISSUE THREAD

**Issue by vemv** [jonase/eastwood#336]
Hi again!

As I tried to upgrade  `[jonase/eastwood "0.3.5"]` -> `[jonase/eastwood "0.3.9"]`, these started to show up:

```
Var reportmm def'd 2 times at line:col locations: formatting_stack/protocols/spec.clj:43:11 formatting_stack/protocols/spec.clj:43:11
```

As you can note, line/col info is identical at both hands of the report.

I'm  100% sure the namespace in question is defined correctly and over a single JVM `resource`.

WDYT?

I could try providing a failing test case.

-V

**Comment by slipset** [comment]
I would really appreciate a minimal repro here, since I cannot seem to be able to reproduce it.

**Comment by slipset** [comment]
I can reproduce it now that I looked at your code. It chokes on the defmulti! That's super strange.
Works perfectly in 0.3.7

Ok, so it was introduced in  10261c29a9c9ebb979d65ceb31ae5a7fcda88705.

**Comment by slipset** [comment]
The same for #337 also worked nicely before 10261c2. Maybe @thumbnail could have a go at that commit again (I believe you're both involved in formatting-stack?

**Comment by slipset** [comment]
Ok, so RTFS'ing a bit more shows me https://github.com/jonase/eastwood/blob/master/resource/eastwood/config/clojure.clj#L8 which leads me to believe that 564c1c2 leads Eastwood to discard all configs altogether.

**Comment by vemv** [comment]
Hi @slipset !

Thanks for taking a look at this one.

We've done `(reset! warning-enable-config-atom [])` in formatting-stack for one year straight, so it's not necessarily a wrong idea.

Maybe https://github.com/jonase/eastwood/commit/564c1c2a3622937f11683a7660b597706ae49dc6 does the `reset!` too early though, or something like that.

I can try a Lein checkout and try to toggle that commit, or other recent commits.

We also might want to try contributing some tests, so that we all regain confidence around changes :)

**Comment by slipset** [comment]
It does it to early. I'm preparing a fix now.
