### ISSUE TITLE
Idea: analyze serially, lint in parallel

### ISSUE THREAD

**Issue by vemv** [jonase/eastwood#339]
## Problem statement

Although https://github.com/jonase/eastwood/tree/81d9c551c345261dcb2676c78034ad9406c9d383#parallelism is a thing, I think performing AST analysis in parallel _in a repl environment_ can be problematic: tools.analyzer performs a `clojure.core/require` as part of its evaluations, and `require` is not thread-safe.

I documented a similar previous experience [here](https://github.com/clojure-emacs/refactor-nrepl/pull/247#issuecomment-561009122).

## Proposal

So, if AST analysis cannot be safely done in parallel, the next big candidate to parallelization would be the execution of the linters themselves.

Here, we can see how the set of linters (by default: 20) is run serially:

https://github.com/jonase/eastwood/blob/81d9c551c345261dcb2676c78034ad9406c9d383/src/eastwood/lint.clj#L168

As per usual, changing `map` -> `pmap` is not magic (as it can easily 'overparallelize' workloads).

However, running a custom `pmap` did succeed in improving the performance. Linting a single big ns (`eastwood.lint`) I saw ~200 ms being shaved. Obviously, these gains could add up nicely when linting a whole project.

## Nuances

* I assume that the 20 linters are pure functions and don't perform further AST evaluations
  * i.e. thread-safety is a prerequisite
* Learning from recent experiences, I'd be careful about introducing `pmap` just like that
  * idea: `(def ^:dynamic *linter-executor* map)`
    * i.e. change nothing, allow consumers to bring `pmap`, a custom `pmap` etc
    * allowing third-party consumers to test out this well, particularly on CI, etc.

WDYT?

**Comment by slipset** [comment]
Thank you for bringing this up. 
Running the linters in parallel was my first idea for speeding up Eastwood, but when I did the analysis it showed that the time spent analyzing was so much greater than the time spent linting, so I tried to focus on analysis. 

But, being able to shave off 200ms for a single ns sounds interesting. 

For reference, linting my work project (~70kloc) takes between four to five minutes.

**Comment by vemv** [comment]
Testing my tentative change more extensively: I got a nice shave from 130s to 80s when linting one of my biggest projects.

As agreed over Slack I'll just introduce a "linter-executor" to be optionally passed as config (not dynvar).

My only hesitation would be around the thread safety of the linters themselves. Having a look they seem safe to me: they have no eval, require, etc. I could only spot a single `eval`:

https://github.com/jonase/eastwood/blob/81d9c551c345261dcb2676c78034ad9406c9d383/src/eastwood/linters/typetags.clj#L145

...but it seems a very delimited `eval`. Sounds correct?

Hope to PR soon!

**Comment by slipset** [comment]
That has been my assumption too, that the linters are thread safe.
The only thing I would be worried about is output, but if I'm not mistaken, the code first collects data, then it outputs, so that should not be a problem.

**Comment by jafingerhut** [comment]
I do not recall any of the linters being anything other than sequential, pure functions of their inputs, and I do not recall any of them using the results of others as inputs.  Caveat: It has been a couple of years since I looked at them.
