### ISSUE TITLE
Eastwood doesn't macroexpand before looking for (ns) forms

### ISSUE THREAD

**Issue by ToxicFrog** [jonase/eastwood#342]
This is a very stripped-down version of real code:
```clojure
; core.clj
(defmacro ns+ [& body]
  `(ns ~@body
     (:require [schema.core :as ~'s :refer ~'[def defn defmethod defschema fn]])
     (:refer-clojure :exclude ~'[def defn defmethod fn])))

(user/ns+ core (:require [misc]))
```
```clojure
; misc.clj
(user/ns+ misc)
```

In this, `user/ns+` is defined to automatically include `schema.core` in any namespace, along with the boilerplate needed to suppress warnings about it hiding builtin definitions. All namespaces in the project use that instead of `ns` for namespace definitions.

This _runs_ fine, but Eastwood emits a bunch of "no ns form found in file <file>. it will not be linted" errors. If I explicitly list them, `core` is linted as if it had no `ns` form, and `misc` crashes eastwood saying that it can't find var `user`.

It looks like two things are going on here:
- it doesn't realize that `user/ns+` macroexpands into `ns`, so all files are treated as if they have no `ns` form
- the side effect that loading `core.clj` is meant to cause (defining `user/ns+`) doesn't actually carry across files, despite the Eastwood documentation saying that all the normal side effects of loading files will still occur.

**Comment by ToxicFrog** [comment]
N.b. this is using `lein eastwood`, not eastwood in the REPL.

**Comment by slipset** [comment]
Unfortunately this is due to how Eastwood uses `tools.namespace` to find files for linting.
`tools.namespace` relies on its own ns-parser and does not use macro expansion to do this work.
