### ISSUE TITLE
Got exception with extra ex-data: msg='Syntax error compiling fn* at (clojure_rte/util_test.clj:282:1).'

### ISSUE THREAD

**Issue by jimka2001** [jonase/eastwood#344]
I just installed lein eastwood for the first time today, by putting the following in my `.lein/profiles.clj` file.
```
{:user {:plugins [jonase/eastwood "0.3.10"]
                  ]}}
```
This was the version recommended in the [README.md](https://github.com/jonase/eastwood) file.

I'm trying to run lein eastwood on my clojure project, and I encounter what appears to be an error in eastwook.  lein eastwood fails on a `clojure.test/deftest` call with large inline data.  I'll attach the `util_test.clj` file, rather than pasting a huge piece of data into this issue text.

Here is the error message I'm receiving.

```
== Linting clojure-rte.util-test ==
Exception thrown during phase :analyze+eval of linting namespace clojure-rte.util-test
Got exception with extra ex-data:
    msg='Syntax error compiling fn* at (clojure_rte/util_test.clj:282:1).'
    (keys dat)=(:clojure.error/phase :clojure.error/line :clojure.error/column :clojure.error/source :clojure.error/symbol)
CompilerException Syntax error compiling fn* at (clojure_rte/util_test.clj:282:1).
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7114)
	clojure.lang.Compiler.analyze (Compiler.java:6789)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7094)
	clojure.lang.Compiler.analyze (Compiler.java:6789)
	clojure.lang.Compiler.analyze (Compiler.java:6745)
	clojure.lang.Compiler$MapExpr.parse (Compiler.java:3104)
	clojure.lang.Compiler.analyze (Compiler.java:6797)
	clojure.lang.Compiler.analyze (Compiler.java:6745)
	clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:594)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7106)
	clojure.lang.Compiler.analyze (Compiler.java:6789)
	clojure.lang.Compiler.analyze (Compiler.java:6745)
	clojure.lang.Compiler.eval (Compiler.java:7180)
	clojure.lang.Compiler.eval (Compiler.java:7131)
	clojure.core/eval (core.clj:3214)
	clojure.core/eval (core.clj:3210)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval/fn--4736 (jvm.clj:585)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval (jvm.clj:585)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval (jvm.clj:528)
	eastwood.analyze-ns/analyze-file/fn--4981/fn--4983 (analyze_ns.clj:326)

... stuff deleted ...

	clojure.main/init-opt (main.clj:454)
	clojure.main/initialize (main.clj:485)
	clojure.main/null-opt (main.clj:519)
	clojure.main/null-opt (main.clj:516)
	clojure.main/main (main.clj:598)
	clojure.main/main (main.clj:561)
	clojure.lang.Var.applyTo (Var.java:705)
	clojure.main.main (main.java:37)
Caused by:
IndexOutOfBoundsException Method code too large!
	clojure.asm.MethodWriter.computeMethodInfoSize (MethodWriter.java:2061)
	clojure.asm.ClassWriter.toByteArray (ClassWriter.java:457)
	clojure.lang.Compiler$ObjExpr.compile (Compiler.java:4668)
	clojure.lang.Compiler$FnExpr.parse (Compiler.java:4106)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7104)
	clojure.lang.Compiler.analyze (Compiler.java:6789)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7094)
	clojure.lang.Compiler.analyze (Compiler.java:6789)
	clojure.lang.Compiler.analyze (Compiler.java:6745)
	clojure.lang.Compiler$MapExpr.parse (Compiler.java:3104)
	clojure.lang.Compiler.analyze (Compiler.java:6797)
	clojure.lang.Compiler.analyze (Compiler.java:6745)
	clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:594)
	clojure.lang.Compiler.analyzeSeq (Compiler.java:7106)
	clojure.lang.Compiler.analyze (Compiler.java:6789)
	clojure.lang.Compiler.analyze (Compiler.java:6745)
	clojure.lang.Compiler.eval (Compiler.java:7180)
	clojure.lang.Compiler.eval (Compiler.java:7131)
	clojure.core/eval (core.clj:3214)
	clojure.core/eval (core.clj:3210)
	eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval/fn--4736 (jvm.clj:585)

```

[util_test.clj.gz](https://github.com/jonase/eastwood/files/4508425/util_test.clj.gz)

**Comment by vemv** [comment]
Although strictly speaking this a bug, that test is not optimally written.

That code would compile huge to . filesclass. It's not acceptable for either vanilla java, vanilla clojure, or Eastwood analyses. In all cases, there's a limit to how much code can be defined per class.

I'd take the bug as a feature: can I use the occasion decomplect code from data? In this case, you can extract the `operands` stuff to an .edn file, and load it in runtime within your test.

A lot of stuff becomes better when separating code from data.

As a last note, code that reaches 8000 columns can easily make IDEs choke!

Hope it helps.

**Comment by jimka2001** [comment]
BTW, being an emacs user I don't get any long line problems, apparently emacs handles it well

**Comment by vemv** [comment]
FWIW (I'm only an occasional Eastwood contributor) `IndexOutOfBoundsException Method code too large!` is not an opinion, is a fact which you can check on google. Code cannot be arbitrarily large on JVM programs - we're not merely talking about column count from a style POV.

I use Emacs also :) it can be bit of a hit-or-miss experience, depends on the exact buffers contents.

If it interests you, there are Clojure linters for column limits, one being https://github.com/dakrone/lein-bikeshed the other being https://github.com/nedap/formatting-stack/ (my creation, which also wraps Eastwood)

**Comment by diptigautam** [comment]
Hi, I got the same issue, and apparently that was because there were just too many methods. If you split it into two different protocols, it will work!
