### ISSUE TITLE
Discouraged var usage

### ISSUE THREAD

**Issue by slipset** [jonase/eastwood#345]
See https://github.com/borkdude/clj-kondo/issues/996

We will need a config to allow for usage of discouraged vars.
This linter should probably not be enabled by default

**Comment by vemv** [comment]
I'll give a shot to this one, long wanted feature for me

(I consider `flatten` and `concat` usual suspects if you ask me)

**Comment by vemv** [comment]
Implemented in https://github.com/clj-kondo/clj-kondo/issues/996

I'm not keen on reimplementing linters, unless there is a realistic win (which practically isn't the case here) for Eastwood's approch to shine
