### ISSUE TITLE
Failing test on master if `:eval-in-leiningen false`

### ISSUE THREAD

**Issue by vemv** [jonase/eastwood#354]
It seems that if one sets `:eval-in-leiningen false` in project.clj locally and then runs `lein with-profile -user do clean, test`, the test suite will fail with:

```
lein test eastwood.test.implicit-dependencies-linter-test
Pretty-printed diffs between actual and expected lint results:
[nil
 {{:linter :implicit-dependencies,
   :msg
   "Var clojure.string/join refers to namespace clojure.string that isn't explicitly required.",
   :file "testcases/implicit_dependencies.clj",
   :line 4,
   :column 3}
  1}]

lein test :only eastwood.test.implicit-dependencies-linter-test/implicit-dependency-linter

FAIL in (implicit-dependency-linter) (implicit_dependencies_linter_test.clj:6)
expected: (clojure.core/= diffs__7700__auto__ [nil nil])
  actual: (not (clojure.core/= [nil {{:linter :implicit-dependencies, :msg "Var clojure.string/join refers to namespace clojure.string that isn't explicitly required.", :file "testcases/implicit_dependencies.clj", :line 4, :column 3} 1}] [nil nil]))
```

I checked this on `master`.

**Comment by vemv** [comment]
Wondering if a PR would be welcome with the following changes?

* Remove `:eval-in-leiningen`
  * it removes flexibility for running tests, repls etc and also can affect test reliability (per my OP)
* remove `leiningen-core` from :dev
  * Seems an odd dep to have, and probably creates more assumptions than needed (e.g. a specific Lein version is being used, or Eastwood is being run via Lein at all, etc)
* Make the test suite able to pass with the :dev profile removed
  * a bit subjective but IMO dev utilities should be segregated from test requirements. Else one cannot be sure if non-essential utilities are affecting the test suite in some way.

**Comment by vemv** [comment]
@slipset @jafingerhut any thoughts?

The common thread among my proposals above is emphasizing that Eastwood is not only a Lein plugin but also a lib that can be invoked from any Clojure project.

**Comment by slipset** [comment]
I do not mind having @vemv as a co-developer. @jonase?
