### ISSUE TITLE
Release 0.3.14 requires Clojure 1.10

### ISSUE THREAD

**Issue by seancorfield** [jonase/eastwood#356]
```
ClassCastException class clojure.lang.Var cannot be cast to class java.lang.String (clojure.lang.Var is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	clojure.core/symbol (core.clj:579)
	clojure.core/symbol (core.clj:574)
	eastwood.linters.implicit-dependencies/var->ns-symbol (implicit_dependencies.clj:8)
	eastwood.linters.implicit-dependencies/var->ns-symbol (implicit_dependencies.clj:7)
	eastwood.linters.implicit-dependencies/implicit-dependencies/fn--5794 (implicit_dependencies.clj:39)
```
This happens on Clojure 1.9 because namespace vars cannot be converted directly to symbols.

I don't know if it was intentional to require Clojure 1.10 for this release?

**Comment by vemv** [comment]
> This happens on Clojure 1.9 because namespace vars cannot be converted directly to symbols.

TIL!

> I don't know if it was intentional to require Clojure 1.10 for this release?

It wasn't, sorry for that

I can contribute a patch to gracefully degrade behavior. Can also be a good chance to implement a simple CI matrix? It's already outlined here: https://github.com/jonase/eastwood/blob/7672782d748bcc15c0ea5bf1d913c3d47c9e0810/project.clj#L36-L41

cc/ @slipset
