### ISSUE TITLE
Consider a linter for bad :as bindings in vectors

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#36]
Not sure if this is a good thing for Eastwood to be checking for or not.  Just wanted to create the issue for future consideration.

See http://dev.clojure.org/jira/browse/CLJ-1309 for more details.

**Comment by vemv** [comment]
> Alex Miller  May 16, 2017, 12:40 AM

> In 1.9, this now throws an error as the spec is violated.
