### ISSUE TITLE
Problem with let-bound shadow var warning?

### ISSUE THREAD

**Issue by carrete** [jonase/eastwood#369]
In reference to #81, when I run eastwood over a fulcro app that uses its `defrouter` macro, I get this warning:

    local-shadows-var: local: factory invoked as function shadows var: #'com.fulcrologic.fulcro.components/factory

I think this is referring to [this section of defrouter](https://github.com/fulcrologic/fulcro/blob/2e38ab328ac4ef9f06778cf117fdc677ceec4aa5/src/main/com/fulcrologic/fulcro/routing/dynamic_routing.cljc#L805-L806):

    (let [~'factory (comp/factory ~'class)]
        (~'factory (comp/computed ~'current-route (comp/get-computed ~'this))))

If the `factory` let-bound var is scoped to the current namespace, and the `factory` function can only be reached via the `comp` namespace, why is this warning being triggered?

**Comment by vemv** [comment]
Thanks for the report!

If possible could you contribute a minimal ns reproducing it? This way one doesn't have to investigate how to set up Fulcro.

Any example suffices - for example you can git-clone Eastwood, add a `foo` ns somewhere and add the minimal code that will ultimately call `defrouter*`.

This is the code to self-lint eastwood (i.e. check that your repro works):

https://github.com/jonase/eastwood/blob/c5b7d9f8ad8f8b38dc7138d853cc65f6987d6058/.circleci/config.yml#L56

**Comment by carrete** [comment]
@vemv, please see [this commit](https://gitlab.com/tvaughan/eastwood/-/commit/cb998f6334500ffdbbacd9cb023a00385dc006a1) and [this test failure](https://gitlab.com/tvaughan/eastwood/-/jobs/1151762849). The warning is triggered [when `factory` is referred to](https://gitlab.com/tvaughan/eastwood/-/commit/cb998f6334500ffdbbacd9cb023a00385dc006a1#d5cb57b35e13888f14d69c8866dd369ae53bf37a_0_3). I think I understand now how the let-bound var of `factory` in the defsc macro clashes with a `factory` that has been referred to in the same namespace where the defsc macro is used. I think the answer is "behaves as expected," right?

FYI, I wasn't able to get this to run using the method you linked to above. I tried both JDK 8 and 11, each failed differently. I've copied the errors to [this gist](https://gist.github.com/carrete/bd3feb254fff4a8ae40f4236f1892615).

**Comment by vemv** [comment]
Hey there!

Kudos for the effort the repro 🙌

>  I think the answer is "behaves as expected," right?

Yes, good observation. Probably there isn't a strong reason why `~'factory` isn't `factory#` instead. Macros generally shouldn't pollute environments outside of their control.

Would be a great issue to open in the Fulcro tracker.

This issue sounds good to close now cc/ @slipset

**Comment by carrete** [comment]
Thanks a lot @vemv. I'll look into a patch for fulco

**Comment by vemv** [comment]
🍻

FWIW I tried to run Eastwood in that project (as an easier alternative to temporarily adding Fulcro to Eastwood), I was able to, but it needed some minimal adaptation first https://github.com/fulcrologic/fulcro/pull/469
