### ISSUE TITLE
Eastwood's leiningen plugin seems broken in v0.4.1

### ISSUE THREAD

**Issue by scarytom** [jonase/eastwood#380]
After upgrading from Eastwood 0.4.0 to 0.4.1 the leiningen task has disappeared.  I have reproduced this with a vanilla leiningen project (created via `lein new`).

Adding `:plugins [[jonase/eastwood "0.4.0"]]` and running `lein help` shows the `eastwood` task in the list
Adding `:plugins [[jonase/eastwood "0.4.1"]]` and running `lein help` shows no `eastwood` task in the list!

**Comment by slipset** [comment]
Yup, we had an issue building the artefact. We'll publish a new one shortly.

**Comment by slipset** [comment]
0.4.2 is out, and should fix this.
