### ISSUE TITLE
No exception from :suspicious-test or :keyword-typos linters if unknown namespace

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#41]
Probably best to implement the string-reading of forms that those two linters do in one place in Eastwood, before any linters are called, and add the results to the linter API.  Then any exception that occurs can be handled cleanly in one place, without so many stack traces being spewed to the output.

**Comment by vemv** [comment]
> This has been done for the :suspicious-test linter already a week or two ago,

(👍)

> The :keyword-typos linter needs a different version of the read-in forms, so it is still susceptible to this problem.

https://github.com/jonase/eastwood/issues/127#issuecomment-1008203664
