### ISSUE TITLE
Disable reflection warnings on Java methods

### ISSUE THREAD

**Issue by simionion** [jonase/eastwood#427]
Per my understanding, using `(set! *warn-on-reflection* false)` in a file should disable reflection errors for java methods (ex: `.right`). Is there something I am missing? Perhaps a better approach/setting?
Thank you.

**Comment by vemv** [comment]
https://github.com/jonase/eastwood/tree/b6cf5e67dec600b7368db012c868103fe8a314ba#reflection is a dedicated linter, so you can disable it altogether or create per file/line disablings with https://github.com/jonase/eastwood/tree/b6cf5e67dec600b7368db012c868103fe8a314ba#ignored-faults.

Hope it helps!
