### ISSUE TITLE
Allow suppression of any linter via Eastwood config files

### ISSUE THREAD

**Issue by jeffkayser** [jonase/eastwood#433]
It would be nice to be able to suppress any linter supported by Eastwood, instead of [the subset supported](https://github.com/jonase/eastwood/blob/master/src/eastwood/util.clj#L930-L951=). What's the reasoning behind disallowing this?

For my use case, I can work around it since I'm calling `eastwood.lint/lint` and just getting back data I can choose to ignore, but it'd be nice to control this using Eastwood's standard configuration mechanism.

**Comment by vemv** [comment]
I think :linters / :exclude-linters / :add-linters is what you're looking for, as documented in https://github.com/jonase/eastwood/tree/323568a076544b98c2105e7652758ddd791509a7#usage

The subset you refer to is not for supressing linters altogther - it's for declaring fine-grained suppressions based on code patterns. [Examples](https://github.com/jonase/eastwood/tree/323568a076544b98c2105e7652758ddd791509a7/resource/eastwood/config).

Finally, it's worth considering the newer [ignored faults](https://github.com/jonase/eastwood/tree/323568a076544b98c2105e7652758ddd791509a7#ignored-faults) mechanism which works on a file/line basis - ideal for occasional exceptions which wouldn't warrant disabling a whole linter.

Issue reports always welcome for false positives/negatives - Eastwood strives to be remarkably accurate, needing little config or suppressing.

Cheers - V
