### ISSUE TITLE
:suspicious-test interaction with binding functions

### ISSUE THREAD

**Issue by NoahTheDuke** [jonase/eastwood#436]
Hey there!

In a test, I'm using `clojure.java.jdbc/with-db-connection`, which acts like `clojure.core/let` where it performs some connection logic and binds the result to the given lhs: `(jdbc/with-db-connection [conn db-spec] ...)`. Inside of the body, I'm querying and asserting, using `clojure.test/is`.

Eastwood warns:

> test/example/example_test.clj:123:4: suspicious-test {:kind :pure-fn-inside-is}: Found (jdbc/with-db-connection ...) form inside testing. This is a pure function with no side effects, and its return value is unused. Did you intend to compare its return value to something else inside of an 'is' expression?

I've tried to disable this warning in my `eastwood-config.clj` file with:
```clojure
(disable-warning {:linter :suspicious-test
                  :for-macro 'clojure.java.jdbc/with-db-connection
                  :if-inside-macroexpansion-of #{'clojure.test/deftest
                                                 'clojure.test/testing}
                  :within-depth 10
                  :reason "False-positive for jdbc"})
```
But for whatever reason, this doesn't help. What is the best way to write the `disable-warning` options to silence these warnings?

**Comment by NoahTheDuke** [comment]
We use this 201 times in 92 files/namespaces lol. To use `:ignored-faults`, I'll have to put 92 entries into my project.clj with either `true` or the line/line+column numbers to match? Bummer. Maybe I'll just disable the linter for now.

Thanks for the quick response.

**Comment by vemv** [comment]
1.2.4 is being released this morning!

**Comment by NoahTheDuke** [comment]
Thank you so much!
