### ISSUE TITLE
:unused-namespaces linter not working properly with clojure.specs

### ISSUE THREAD

**Issue by luisfernando37** [jonase/eastwood#437]
If I need to check if a field is valid using specs, I'd do `(s/valid? :party/field "value")`, for doing this checking I should require the ns where I'm defining :party/field `(s/def :party/field ...)` like this `(:require [my-specs])`, In this case the linter throws alerting that `my-specs` is not being used, which is false since it's actually used and required to work with specs validations.

**Comment by vemv** [comment]
Hi!

Thanks for the report. `:unused-namespaces` isn't enabled by default, also it's not the sort of thing that Eastwood aims to shine at.

clojure-lsp has a linter for unused vars and such.

You could use that one while still using Eastwood for things it will uniquely lint.

Other that I don't plan to improve `:unused-namespaces`. (PRs welcome)
