### ISSUE TITLE
Feature request: Move config options into config-file

### ISSUE THREAD

**Issue by NoahTheDuke** [jonase/eastwood#438]
Hey there! I like to keep my `project.clj` focused, and including all of the eastwood config details in it feels messy to me. Would it be possible to add a function similar to `disable-warning` that I can call at the top of one of my `:config-files` files? Something like:

```clojure
(setup-config
  {:linters [:all]
   :exclude-linters [:implicit-dependencies
                     :keyword-typos]})

(disable-warning
  ,,,)
```

And then the only eastwood config I need to include in my project.clj is `:config-files ["eastwood_config.clj"]`.

**Comment by vemv** [comment]
Hi there!

I'll check it out what we have, else surely it would be easy to add this, yes.

**Comment by vemv** [comment]
WDYT of extracting the eastwood config to a profiles.clj file within your project root? (https://github.com/technomancy/leiningen/blob/24fb93936133bd7fc30c393c127e9e69bb5f2392/doc/PROFILES.md#declaring-profiles)

It would look like this:

```clj
{:eastwood {:plugins [[jonase/eastwood "1.2.4"]]
            :eastwood #_::your-config-here}}
```

As you can see it not only tidies up the config, but also a plugin declaration (it's great to run plugins in isolation anyway).

I'd much favor a no-code solution - it means less stuff to maintain.

**Comment by NoahTheDuke** [comment]
Thanks for the suggestion!

The issue isn't so much that I have it inside `:dev` or another profile, but that for clarity on my rapidly growing dev team, I've found it necessary to list every single lint we're using and then also list the lints we're excluding but want to include later. (The goal is for any given dev to look at the list of excluded lints and say, "I have a free hour, I can remove this entry and fix a couple warnings/errors.")

However, this makes for a _long_ entry in the file regardless of where it's sitting:

```clojure
:eastwood {:linters [:bad-arglists
                     :constant-test
                     :def-in-def
                     :deprecations
                     :implicit-dependencies
                     :local-shadows-var
                     :misplaced-docstrings
                     :no-ns-form-found
                     :non-clojure-file
                     :non-dynamic-earmuffs
                     :performance
                     :redefd-vars
                     :reflection
                     :suspicious-expression
                     :suspicious-test
                     :unlimited-use
                     :unused-meta-on-macro
                     :unused-ret-vals
                     :wrong-arity
                     :wrong-ns-form
                     :wrong-pre-post
                     :wrong-tag]
           :exclude-linters [:implicit-dependencies
                             :suspicious-expression
                             :suspicious-test
                             :reflection]
           :config-files ["./eastwood_config.clj"]}
```

I realize that I'm far outside of the norm, lol, and no-code solutions are much better than more-code. If this isn't something you want to support, I totally understand.

If you _would_ be willing to entertain this, I think it could be relatively simple. Could look something like this:

```clojure
; eastwood/util.clj
(def final-config-atom (atom {})

(defn set-config [m]
  (assert (map? m) "map plz")
  (swap! final-config-atom m))

(defn disable-warning [m]
  (swap! warning-enable-config-atom conj m))

; eastwood/lint.clj
(defn last-options-map-adjustments [opts _reporter]
  (let [{:keys [_namespaces] :as opts} (merge default-opts opts @utils/file-config-atom)
```

I'd be willing to write up the PR for it as well, just to limit the amount of work needed on your part.

**Comment by vemv** [comment]
> (The goal is for any given dev to look at the list of excluded lints and say, "I have a free hour, I can remove this entry and fix a couple warnings/errors.")

I would suggest a different approach: don't disable any linters, and leverage https://github.com/jonase/eastwood#ignored-faults instead, declaring fine-grained faults

That way, you don't keep possibly adding _more_ bugs over time, given the linter is disabled altogether.

Devs still get the benefit of looking at a piece of data and say "ok, I have a free hour...".

LMK what you think of this alternative first.

Thanks!

**Comment by vemv** [comment]
:ignored-faults would compose nicely with a profiles.clj located at the project root. Had you thought of that possiblity?

So the big blob of data gets out of the way.

**Comment by vemv** [comment]
> it's not reasonable for us to ever use the {:line n :column m} form of :ignored-faults. 

Have you noticed that :ignored-faults can also work on a per-ns basis?

**Comment by NoahTheDuke** [comment]
> :ignored-faults would compose nicely with a profiles.clj located at the project root. Had you thought of that possiblity?

I didn't know about `profiles.clj` at all, so this is quite intruiging. I'll explore it!

And yes, I used the specific one but like I said in that comment, I have 134 offending namespaces so I don't want 134 extra lines in my project.clj, lol.

Tough decisions all around.

**Comment by vemv** [comment]
134 is better than 403 though 😇

I'll close this issue mostly because there's already the possibility of invoking Eastwood as vanilla lib ([example](https://github.com/nedap/formatting-stack/blob/v4.6.0/src/formatting_stack/linters/eastwood.clj)).

Of course, programmatic usage can pass custom config, and the way config is gathered from users would be under your control.

So you could make your own Lein plugin for instance.

But I really believe that a profiles.clj with 134 lines would be the right approach. It's just data. Data, unlike code, can scale linearly without an associated complexity cost.

Feel free to reach out with related questions over this thread.

Cheers - V

**Comment by vemv** [comment]
btw, one possibly neat feature for Eastwood would be to _emit_ the `:ignored-faults` necessary for a build to pass. Using the whole-namespace notation if desired.

e.g. it could spit this to stdout:

```clj
{:implicit-dependencies {'example.namespace true, 'another.namespace true} 
 :unused-ret-vals       {'yet.another.namespace true}
.,,,
}
```

...so you'd just simply paste that into profiles.clj.

PR would be much welcome for that.

**Comment by NoahTheDuke** [comment]
> Data, unlike code, can scale linearly without an associated complexity cost.

I won't belabor the point as you've stated your position multiple times, both here and in the PR I linked, and I respect your decision to develop this as you see fit, but I do want to respond to this.

What I'm asking for here isn't simply "more code" to solve my problem; I'm asking to expose another, simpler way for me to continue to treat my eastwood configuration as data. Right now, Eastwood's "just data" configuration requires understanding leiningen's (in my opinion) poor semantics and poor discoverability. I understand the value of relying on the host environment (it's Clojure's whole deal!), but in this case, the same "just data" could be achieved in a single function call.

Looks like the `profiles.clj` will probably work for my team which is great. With formatting, 438 total lines, lol. Quiet a few things to ignore and a lot of good clean up work ahead of us.

**Comment by vemv** [comment]
> the same "just data" could be achieved in a single function call.

but that single function call would still have to pass the same data, right? So you still express 26 lines ([per](https://github.com/jonase/eastwood/issues/438#issuecomment-1218066738)) _and_ a function call.

Honestly I don't understand the problem to begin with. Having worked with project.clj files totalling 300+ lines, adding 26 doesn't seem troubling.

Then again Lein has various ways to hide this data e.g. profiles.clj and also eval:

`:eastwood ~(slurp "eastwood-data.edn")`

Hope you can make the most out these linters.

Cheers - V

**Comment by NoahTheDuke** [comment]
> So you still express 26 lines (per) and a function call.

Yeah, if even one new function call is anathema, then this is totally understandable.

> `:eastwood ~(slurp "eastwood-data.edn")`

Okay, what the hell. How did I not know about this haha. (The leiningen docs are so bad...) This will work perfectly for me.

My apologies for the extensive back and forth, and thank you for your patience in answering all of my questions and responding to me.

**Comment by vemv** [comment]
No issue! Happy to help and that Eastwood is being useful at the scale you mention.
