### ISSUE TITLE
Using `:as-alias` triggers a circular dependency error

### ISSUE THREAD

**Issue by NoahTheDuke** [jonase/eastwood#439]
Hey vemv!

It seems that using `:as-alias` triggers a circular-dependency error, even tho `:as-alias` doesn't actually resolve or load the namespace. I get the error:

```bash
$ lein eastwood
WARNING: parse-long already refers to: #'clojure.core/parse-long in namespace: taoensso.carmine, being replaced by: #'taoensso.carmine/parse-long
WARNING: parse-double already refers to: #'clojure.core/parse-double in namespace: taoensso.carmine, being replaced by: #'taoensso.carmine/parse-double
2022-08-29T20:20:07.719Z cb-dell INFO [org.eclipse.jetty.util.log:186] - Logging initialized @21338ms
== Eastwood 1.2.4 Clojure 1.11.1 JVM 11.0.16 ==
Unknown error: {:reason :eastwood.copieddeps.dep9.clojure.tools.namespace.dependency/circular-dependency, :node redacted.internal.namespace, :dependency redacted.other.namespace}
```

Demonstration it's allowed:

```clojure
; src/a.clj
(ns a
  (:require b))
```

```clojure
; src/b.clj
(ns b
  (:require [a :as-alias a-long]))

(println ::a-long/asdf)
```

In your terminal:
```bash
$ clojure
user=> (load "a")
:a/asdf
nil
```

**Comment by vemv** [comment]
Thanks! Looks like a matter of upgrading t.n https://github.com/clojure/tools.namespace/commit/1def04123bcf3772c35c15c7c7f68242615e9b8f

**Comment by vemv** [comment]
Releasing as 1.2.5

Thanks for the report!

How the Eastwood adoption going in the large project you mentioned?

**Comment by NoahTheDuke** [comment]
Thank you for the quick fix! Much appreciated.

> How the Eastwood adoption going in the large project you mentioned?

It's slow going but we're making steady progress! I'm hoping to enforce no reflection in the whole app by the end of September.
