### ISSUE TITLE
data_readers.cljc is not properly excluded

### ISSUE THREAD

**Issue by aldazosa** [jonase/eastwood#447]
I'm encountering a problem when using tagged literals from clj and cljs via a .cljc file with Eastwood. Currently, Eastwood is generating the following warning:

```
src/cljc/data_readers.cljc:1:1: no-ns-form-found: No 'ns' form was found in the file 'src/cljc/data_readers.cljc'. Consequently, it will not be linted.
```
Upon investigating the source code for [eastwood.linters.misc/no-ns-form-found-files](https://github.com/jonase/eastwood/blob/441e3781293bcca13ccd087c099ed2f2ff40ce5b/src/eastwood/linters/misc.clj#L1002), it seems that the exclusion for the "no-ns-form-found" warning applies to the Clojure version of the data readers but not the .cljc file.

### Steps to Reproduce:

1. Create a `data_readers.cljc` file with a map used for tagged literals.
2. Run Eastwood linting.
3. A no namespace warning is shown in the results.

### Expected Behavior:

`data_readers.cljc` file should be excluded (similar to the Clojure version) and not trigger the "no-ns-form-found" warning.

### Actual Behavior:

The `data_readers.cljc` file generates the "no-ns-form-found" warning.

**Comment by vemv** [comment]
1.4.1 should be visible on https://clojars.org/jonase/eastwood within an hour.

Cheers - V
