### ISSUE TITLE
Bump old `asm-all 5.2` version

### ISSUE THREAD

**Issue by mrkam2** [jonase/eastwood#448]
I see that eastwood depends on `[org.ow2.asm/asm-all "5.2"]` https://github.com/jonase/eastwood/blob/master/project.clj#L31C19-L31C44 which is conflicting with the most current version `org.ow2.asm/asm 9.2` that is, for example, a dependency of `org.clojure/tools.analyzer.jvm 1.2.2` which is a dependency of `org.clojure/core.async 1.6.673`. The two libraries share a lot of classes but some are only available in `asm-all`, such as `org/objectweb/asm/tree/*`, `org/objectweb/asm/util/*`, `org/objectweb/asm/commons/*`, `org/objectweb/asm/xml/*` and I'm unsure whether eastwood depends on any of them. Has it been considered to upgrade this dependency?

It actually looks like eastwood works fine with `org.ow2.asm/asm 9.2`, at least in terms of running linter on our projects when I used the following entry in my deps.edn file:
```
jonase/eastwood {:mvn/version "1.3.0"
                           :exclusions [org.ow2.asm/asm-all]}
```

**Comment by vemv** [comment]
Thanks much!

We use antq, but looks like the slightly different dep name got to trick it.

Will upgrade.

**Comment by vemv** [comment]
Expect Eastwood 1.4.2 to be visible within a few minutes.

Cheers - V
