### ISSUE TITLE
New linter to warn about mismatch between :arglists and actual fn args

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#51]
:arglists is sometimes modified by library developers in an attempt to document variations on argument lists when there are many possibilities.  Nicola has pointed out that the Clojure documentation for def [1] says  that :arglists will be "a list of vector(s) of argument forms, as were supplied to defn" and the clojure Compiler uses :arglists for type-hints handling.

http://clojure.org/special_forms#Special%20Forms--%28def%20symbol%20init?%29

The warning message should have a brief description, perhaps with a link to a section of the Eastwood docs explaining the situation, and what is recommended instead.  Bonus points if reply changes 'doc' macro check for a different keyword like :doc-arglists before :arglists (or shows both if they both exist)

**Comment by muhuk** [comment]
I'm having the exact same issue with @lvh.

**Comment by jafingerhut** [comment]
I have cloned the icecap project mentioned above: https://github.com/lvh/icecap

I have this commit id: cadaeb01f81ff4b886d5d44db3609a32b1c7229c

I have run 'lein eastwood' with Eastwood versions 0.1.4 through 0.2.2 in the root directory of this project, and do not see any :bad-arglists warnings at all.

Can you reproduce the warning using 'lein eastwood', perhaps with some extra command line options?

If not, what command line can you reproduce it with?

**Comment by muhuk** [comment]
@jafingerhut in [my case](http://dev.clojure.org/jira/browse/TCHECK-86) I don't have `icecap` as a dep. No special command, just `lein eastwood`.

If you can't reproduce I can try creating a minimal project and pust it to GH.

**Comment by jafingerhut** [comment]
I see a similar bad-arglists warning when I run Eastwood version 0.2.1 on the automat project, which uses defspec from test.check.

I made some changes to the bad-arglists linter in Eastwood version 0.2.2, very recently released, which eliminate that warning.  Can you try out Eastwood 0.2.2 to see if it helps in your case, too?

**Comment by muhuk** [comment]
I've just checked with `0.2.2` and that warning is gone. Awesome! Thanks.

**Comment by lvh** [comment]
Same here, thanks!

**Comment by jafingerhut** [comment]
bad-arglists linter seems to be in a reasonable state as of Eastwood 0.2.2 release.  All issues raised in the comments for this issue are either taken care of, have a separate issue raised for them, except for the :doc-arglists idea, which is a suggested change in Clojure itself that is unlikely to occur.
