### ISSUE TITLE
Eastwood fails to analyze some core.typed source

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#70]
For example, here:

== Linting clojure.core.typed.macros ==
Linting failed:
ExceptionInfo Invalid token: ::t/fn
    clojure.core/ex-info (core.clj:4327)
    eastwood.copieddeps.dep10.clojure.tools.reader.reader-types/reader-error (reader_types.clj:337)

That file has early in it this line: (alias 't 'clojure.core.typed)
and later this keyword: ::t/fn

Nicola believes that since Eastwood does eval the first form after reading it, before reading the rest of the file, it should be able to read the later symbol without an error.

Perhaps Eastwood is not eval'ing the first form in such a way that tools.reader picks up the alias?  Not an urgent issue, since core.typed is the only project out of many that I have seen use this method, but it would be nice to enhance some time if it isn't too difficult.

**Comment by vemv** [comment]
core.typed has changed a bit over the years both technically and in terms of adoption.

Whenever it becomes a 'player' in the scene again we could take a look at any issues Eastwood might have with it 👀
