### ISSUE TITLE
eastwood should warn about using `get` on atom instead of atom's map

### ISSUE THREAD

**Issue by uvtc** [jonase/eastwood#76]
I'd expect `lein eastwood` to warn me about the following:

``` clojure
(def m (atom {:a 1 :b 2}))

(get m :a)  ; expecting 1, got nil

;; because that was a typo, and should've been:
(get @m :a)  ;=> 1
```

but eastwood doesn't mention that `(get m :a)` looks fishy.

**Comment by vemv** [comment]
clj-kondo has some work in the "type checking from heuristics" area https://github.com/clj-kondo/clj-kondo/blob/master/doc/types.md

I think that's super useful and probably the most one can achieve (aside from a non-linter-based approach e.g. Spec, Malli, etc).

Eastwood is generally focused in implementing linters that can work with all certainty (no false positives / false negatives). So as @gfredericks says, there isn't a general way to achieve this so I don't foresee Eastwood trying to bother.
