### ISSUE TITLE
Warn about unused dependencies in project.clj

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#82]
I am not sure how to implement this idea right now, but it seems like info that a developer would sometimes want to know, to trim their dependency list.  Request originally from @kolemannix in comments on issue #11

**Comment by vemv** [comment]
@borkdude 's https://github.com/borkdude/deps-infer seems a good basis for creating such a linter.

This sort of thing seems to go a bit beyond Eastwood's scope (namely tools.analyzer-powered form linting) so I propose to close this issue for keeping the tracker tractable
