### ISSUE TITLE
Consider linter to check keyword args in fn calls against expected keywords in defn

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#83]
Link to Clojure Google group discussion: https://groups.google.com/forum/#!topic/clojure/GzHwarVqLjY

Copy of original message from Dave Tenny describing the problem:

```
user> (defn foo [& {:keys [bar]}] bar)
#'user/foo
user> (foo :baz 1)
nil
```

In my opinion the compilation of the call to foo should have complained about :baz not matching a known parameter.

Failure to do this leads to lots of extra debugging because someone had a typo in a keyword name,
e.g. ":Name" instead of ":name" or :product instead of :project, or whatever.

This is probably the leading cause of unexpected program operation in clojure for me.

**Comment by vemv** [comment]
This sounds like static analysis territory - beyond what even a well-implemented tools.analyzer tool could infer (that is, 100% of the time)

A fairly idiomatic option these days would be to back `defn` with Spec, Malli etc and catch any required non-passed kwarg at runtime.
