### ISSUE TITLE
use MrAnderson instead of copieddeps?

### ISSUE THREAD

**Issue by benedekfazekas** [jonase/eastwood#87]
while working on [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl) I faced similar problems what you guys faced with eastwood (clashing on dependencies with projects I wanted to use the refactor tool on). Your copieddeps readme was a great resource to think about this problem btw. Anyways I came up with an automated solution as a leiningen plugin: [mranderson](https://github.com/benedekfazekas/mranderson).

I am sure there are plenty of rough edges but it does the trick for me: it might solve the problem eastwood is solving manually with copieddeps too.

**Comment by vemv** [comment]
I wonder if this issue should be closed as there aren't other issues related to `dolly` and it seems a good approach overall.

mranderson is very much a reputed project by now, but personally I wouldn't change what isn't broken, particularly when maintainer time is a scarce resource :)
