### ISSUE TITLE
Wrong file/line/column combinations in warnings

### ISSUE THREAD

**Issue by jafingerhut** [jonase/eastwood#91]
I think this has been around for a while, but I haven't created an issue to track it yet.  Most recently I recall seeing this issue for some warnings with Eastwood 0.1.5-alpha1 and a 0.3.2-SNAPSHOT version of Prismatic's schema library: https://github.com/Prismatic/schema

I don't know the exact conditions or cause of the problem yet, but it definitely seems to be that line/column numbers from one file are combined with a file name of a different file, one that might not even have that many lines as shown in the warning.  The line/column numbers appear to be from another file, macros seem to be involved, and it seems that the ASTs produced by tools.analyzer.jvm are tacking on a file name to an AST or its :env when there was none (perhaps because the namespace was read with the default Clojure reader, rather than tools.reader?), and it seems like it shouldn't be doing that.

More details as I investigate.  Will probably turn into a TANAL ticket if I can narrow it down a bit.

**Comment by vemv** [comment]
>  perhaps some of these have been fixed with code updates in tools.reader and/or tools.analyzer(.jvm) that I haven't even noticed exactly when things changed.

In face of this and the lack of significative line/col mismatches I've perceived over the last few years, I'll close the issue.
